// playground/src/components/shared/ContextHeader.vue
<!--
  ContextHeader.vue — sticky "what am I looking at" header shown at the
  top of a diagnostic tab: an eyebrow label, the active line badge
  (`L{n}` or "All Lines"), and the expression text being diagnosed.

  Extracted from three near-identical bespoke implementations that used
  to live separately in PipelineTab, NormalizerTab, and
  ParseletRegistryTab. Also used by BytecodeTab and VmTraceTab, which
  previously had no context header at all.
-->
<template>
  <div class="diag-context-header">
    <div class="diag-context-left">
      <span class="diag-context-label">{{ label }}</span>
      <span class="diag-context-badge">{{ lineBadge }}</span>
    </div>
    <span class="diag-context-expr" :title="expression">{{ expression || '(empty expression)' }}</span>
    <div v-if="$slots.extra" class="diag-context-extra">
      <slot name="extra" />
    </div>
  </div>
</template>

<script setup lang="ts">
defineProps<{
  /** Eyebrow label, e.g. "Normalizing", "Pipeline", "Parselets". */
  label: string;
  /** Compact line indicator, e.g. "L3" or "All Lines". */
  lineBadge: string;
  /** The active expression text being diagnosed. */
  expression: string;
}>();
</script>

// webapp/src/components/shared/ContextHeader.tsx
import type { ReactNode } from "react"
import { Badge } from "@/components/ui/badge"

/**
 * Sticky "what am I looking at" header shown at the top of a diagnostic
 * tab: an eyebrow label, the active line badge (`L{n}` or "All Lines"),
 * and the expression text being diagnosed.
 *
 * Ported from playground's ContextHeader.vue — used by Pipeline, Normalizer,
 * ParseletRegistry, Bytecode, and VmTrace tabs.
 */
export function ContextHeader({
  label,
  lineBadge,
  expression,
  extra,
}: {
  /** Eyebrow label, e.g. "Normalizing", "Pipeline", "Parselets". */
  label: string
  /** Compact line indicator, e.g. "L3" or "All Lines". */
  lineBadge: string
  /** The active expression text being diagnosed. */
  expression: string
  extra?: ReactNode
}) {
  return (
    <div className="bg-card sticky top-0 z-10 flex items-center gap-3 border-b px-4 py-2">
      <div className="flex shrink-0 items-center gap-2">
        <span className="text-muted-foreground text-xs font-medium tracking-wide uppercase">
          {label}
        </span>
        <Badge variant="secondary">{lineBadge}</Badge>
      </div>
      <span
        className="min-w-0 flex-1 truncate font-mono text-sm"
        title={expression}
      >
        {expression || "(empty expression)"}
      </span>
      {extra && <div className="shrink-0">{extra}</div>}
    </div>
  )
}
