// webapp/src/components/tabs/CacheTab.tsx
import { useEffect, useMemo, useState } from "react"
import { Database, Grid3x3, Braces, BarChart3, Table, Radio, CloudCog, TrendingUp, TrendingDown, ArrowRight, ChevronDown, ChevronRight } from "lucide-react"
import type { QueryCacheEntry } from "@bridge/engine"
import type { CacheHistoryEntry } from "@/stores/diagnosticReport"
import { useDiagnosticReportStore } from "@/stores/diagnosticReport"
import { formatDuration } from "@bridge/utils"
import { EmptyState } from "@/components/shared/EmptyState"
import { cn } from "@/lib/utils"

function hitRatePct(entry: CacheHistoryEntry): number {
  const total = entry.cacheHits + entry.cacheMisses
  return total > 0 ? Math.round((entry.cacheHits / total) * 100) : 0
}

function formatAge(createdAt: number, nowMs: number): string {
  const diffMs = nowMs - createdAt
  if (diffMs < 0) return "just now"
  const sec = Math.floor(diffMs / 1000)
  if (sec < 60) return `${sec}s`
  const min = Math.floor(sec / 60)
  if (min < 60) return `${min}m`
  return `${Math.floor(min / 60)}h`
}

function freshnessPct(entry: QueryCacheEntry, nowMs: number): number {
  if (!entry.staleTime || entry.staleTime <= 0) return 0
  const elapsed = nowMs - entry.updatedAt
  return Math.min(100, Math.max(0, (elapsed / entry.staleTime) * 100))
}

function freshnessBarClass(entry: QueryCacheEntry, nowMs: number): "bg-emerald-500" | "bg-amber-500" | "bg-destructive" {
  if (!entry.staleTime || entry.staleTime <= 0) return "bg-emerald-500"
  const pct = freshnessPct(entry, nowMs)
  if (pct < 50) return "bg-emerald-500"
  if (pct < 90) return "bg-amber-500"
  return "bg-destructive"
}

function freshnessBarTitle(entry: QueryCacheEntry, nowMs: number): string {
  if (!entry.staleTime || entry.staleTime <= 0) return "Never stale"
  const elapsed = nowMs - entry.updatedAt
  const remaining = Math.max(0, entry.staleTime - elapsed)
  if (remaining <= 0) return "Stale — data may be refetched on next access"
  const sec = Math.floor(remaining / 1000)
  if (sec < 60) return `${sec}s until stale`
  const min = Math.floor(sec / 60)
  if (min < 60) return `${min}m until stale`
  return `${Math.floor(min / 60)}h until stale`
}

/** Ported from playground's CacheTab.vue. */
export function CacheTab() {
  const cache = useDiagnosticReportStore((s) => s.cacheSnapshot)
  const heatmapEntries = useDiagnosticReportStore((s) => s.pageHeatmap)
  const queryCacheEntries = useDiagnosticReportStore((s) => s.queryCache)
  const cacheHistoryEntries = useDiagnosticReportStore((s) => s.cacheHistory)

  const [nowMs, setNowMs] = useState(() => Date.now())
  const [trendView, setTrendView] = useState<"hitmiss" | "size">("hitmiss")
  const [expandedKeys, setExpandedKeys] = useState<Record<string, boolean>>({})

  useEffect(() => {
    const id = setInterval(() => setNowMs(Date.now()), 1000)
    return () => clearInterval(id)
  }, [])

  function toggleExpand(key: string) {
    setExpandedKeys((prev) => ({ ...prev, [key]: !prev[key] }))
  }

  const resolvedLineCount = (cache?.lineCache ?? []).filter((e) => e.resultType !== "Pending").length
  const asyncCacheEntries = cache?.asyncCache ?? []
  const queryCacheFreshCount = queryCacheEntries.filter((e) => e.status === "fresh").length
  const queryCacheStaleCount = queryCacheEntries.filter((e) => e.status === "stale").length

  const overallHitRate = useMemo(() => {
    if (cacheHistoryEntries.length === 0) return 0
    let totalHits = 0,
      totalLines = 0
    for (const e of cacheHistoryEntries) {
      totalHits += e.cacheHits
      totalLines += e.cacheHits + e.cacheMisses
    }
    return totalLines > 0 ? Math.round((totalHits / totalLines) * 100) : 0
  }, [cacheHistoryEntries])

  const maxHitMissTotal = useMemo(() => Math.max(0, ...cacheHistoryEntries.map((e) => e.cacheHits + e.cacheMisses)), [cacheHistoryEntries])
  const maxBytecodeSize = useMemo(() => Math.max(0, ...cacheHistoryEntries.map((e) => e.bytecodeCacheSize)), [cacheHistoryEntries])

  function hitBarPct(entry: CacheHistoryEntry) {
    return maxHitMissTotal === 0 ? 0 : Math.round((entry.cacheHits / maxHitMissTotal) * 100)
  }
  function missBarPct(entry: CacheHistoryEntry) {
    return maxHitMissTotal === 0 ? 0 : Math.round((entry.cacheMisses / maxHitMissTotal) * 100)
  }
  function bytecodeBarPct(entry: CacheHistoryEntry) {
    return maxBytecodeSize === 0 ? 0 : Math.round((entry.bytecodeCacheSize / maxBytecodeSize) * 100)
  }

  const preloadDirection = useMemo<"forward" | "backward" | "stable" | null>(() => {
    if (heatmapEntries.length < 2) return null
    const trend = heatmapEntries.reduce((acc, entry, i) => {
      if (i === 0) return 0
      const diff = entry.accessSeq - heatmapEntries[i - 1].accessSeq
      return acc + (diff > 0 ? 1 : diff < 0 ? -1 : 0)
    }, 0)
    if (trend > 0) return "forward"
    if (trend < 0) return "backward"
    return "stable"
  }, [heatmapEntries])

  const preloadDirectionTitle =
    preloadDirection === "forward"
      ? "Heuristic: recently-accessed pages trend toward higher page numbers"
      : preloadDirection === "backward"
        ? "Heuristic: recently-accessed pages trend toward lower page numbers"
        : preloadDirection === "stable"
          ? "Heuristic: no clear directional trend in recent page access"
          : ""

  if (!cache) {
    return (
      <div className="flex-1 overflow-y-auto p-4">
        <EmptyState icon={Database} text="No cache data" hint="Evaluate an expression to see cache diagnostics." />
      </div>
    )
  }

  return (
    <div className="flex-1 space-y-4 overflow-y-auto p-4">
      {/* Page Cache */}
      {heatmapEntries.length > 0 && (
        <div>
          <div className="text-muted-foreground mb-1.5 text-[10px] font-semibold tracking-wide uppercase">Page Cache</div>
          <div className="rounded-md border">
            <div className="bg-muted/50 flex flex-wrap items-center gap-2 border-b px-3 py-1.5">
              <span className="flex items-center gap-1.5 text-sm font-medium">
                <Grid3x3 className="size-3.5" /> Page Heatmap
              </span>
              <span className="text-muted-foreground text-xs">{heatmapEntries.length} pages · 128 lines/page</span>
              {preloadDirection && (
                <span title={preloadDirectionTitle} className="text-primary ml-auto flex items-center gap-1 text-xs">
                  {preloadDirection === "forward" ? <TrendingUp className="size-3" /> : preloadDirection === "backward" ? <TrendingDown className="size-3" /> : <ArrowRight className="size-3" />}
                  {preloadDirection} (recent trend)
                </span>
              )}
            </div>
            <div className="flex flex-wrap gap-1.5 p-3">
              {heatmapEntries.map((page) => (
                <div
                  key={page.pageNum}
                  title={`Page ${page.pageNum} (L${page.startLine}-${page.endLine})\nTemp: ${page.temperature}\nAccess: #${page.accessSeq}`}
                  className={cn(
                    "flex w-16 flex-col items-center rounded-md border px-1.5 py-1 text-center",
                    page.temperature === "hot" && "border-destructive/30 bg-destructive/10",
                    page.temperature === "warm" && "border-amber-500/30 bg-amber-500/10",
                    page.temperature === "cold" && "bg-muted",
                  )}
                >
                  <span className="text-xs font-bold">{page.pageNum}</span>
                  <span className="text-muted-foreground text-[9px]">
                    {page.startLine}–{page.endLine}
                  </span>
                </div>
              ))}
            </div>
            <div className="text-muted-foreground flex flex-wrap items-center gap-3 border-t px-3 py-1.5 text-[10px]">
              <span className="text-destructive">● Hot</span>
              <span className="text-amber-600 dark:text-amber-400">● Warm</span>
              <span>● Cold</span>
              <span>Hot = viewport ±3 pages · Warm = viewport ±6 pages · Cold = beyond</span>
            </div>
          </div>
        </div>
      )}

      {/* Bytecode & Line Cache */}
      <div className="space-y-3">
        <div className="text-muted-foreground text-[10px] font-semibold tracking-wide uppercase">Bytecode &amp; Line Cache</div>

        <div className="rounded-md border">
          <div className="bg-muted/50 flex items-center gap-2 border-b px-3 py-1.5">
            <span className="flex items-center gap-1.5 text-sm font-medium">
              <Braces className="size-3.5" /> Bytecode Cache
            </span>
            <span className="text-muted-foreground ml-auto text-xs">{cache.bytecode.length} entries</span>
          </div>
          {cache.bytecode.length === 0 ? (
            <div className="text-muted-foreground p-3 text-center text-sm">No bytecode cache entries</div>
          ) : (
            <div className="p-1">
              <div className="text-muted-foreground px-2 py-1 text-[10px]">
                op = opcodes, num = numeric constants, str = string constants; async = contains an async-resolved data source.
              </div>
              {cache.bytecode.map((entry) => (
                <div key={entry.expression} className="hover:bg-muted/50 flex items-center gap-2 rounded-sm px-2 py-1 font-mono text-xs">
                  <span className="min-w-0 flex-1 truncate">{entry.expression}</span>
                  <span className="text-muted-foreground shrink-0 text-[10px]">
                    {entry.opcodesLength} op · {entry.numbersLength} num · {entry.stringsLength} str
                    {entry.hasAsync ? " · async" : ""}
                  </span>
                </div>
              ))}
            </div>
          )}
        </div>

        {cacheHistoryEntries.length > 1 && (
          <div className="rounded-md border">
            <div className="bg-muted/50 flex flex-wrap items-center gap-2 border-b px-3 py-1.5">
              <span className="flex items-center gap-1.5 text-sm font-medium">
                <BarChart3 className="size-3.5" /> Cache Trends
              </span>
              <span className="text-muted-foreground text-xs">Last {cacheHistoryEntries.length} runs</span>
              <div className="ml-auto flex gap-1">
                <button
                  type="button"
                  onClick={() => setTrendView("hitmiss")}
                  className={cn("rounded px-2 py-0.5 text-[10px]", trendView === "hitmiss" ? "bg-primary text-primary-foreground" : "bg-muted text-muted-foreground")}
                >
                  Hit/Miss
                </button>
                <button
                  type="button"
                  onClick={() => setTrendView("size")}
                  className={cn("rounded px-2 py-0.5 text-[10px]", trendView === "size" ? "bg-primary text-primary-foreground" : "bg-muted text-muted-foreground")}
                >
                  Size
                </button>
              </div>
            </div>
            <div className="space-y-1 p-3">
              {trendView === "hitmiss" ? (
                <>
                  {cacheHistoryEntries.map((entry) => (
                    <div
                      key={entry.runId}
                      title={`Run #${entry.runId}: ${entry.cacheHits} hits / ${entry.cacheMisses} misses = ${hitRatePct(entry)}% hit rate`}
                      className="grid grid-cols-[3rem_1fr_2.5rem] items-center gap-2 text-[10px]"
                    >
                      <span className="text-muted-foreground font-mono">#{entry.runId}</span>
                      <div className="bg-muted flex h-3 overflow-hidden rounded-sm">
                        <div className="flex items-center justify-center bg-emerald-500/60 text-[8px] text-white" style={{ width: `${hitBarPct(entry)}%` }}>
                          {entry.cacheHits || ""}
                        </div>
                        <div className="bg-destructive/60 flex items-center justify-center text-[8px] text-white" style={{ width: `${missBarPct(entry)}%` }}>
                          {entry.cacheMisses || ""}
                        </div>
                      </div>
                      <span className="text-muted-foreground text-right">{hitRatePct(entry)}%</span>
                    </div>
                  ))}
                  <div className="text-muted-foreground flex items-center gap-3 pt-1 text-[9px]">
                    <span className="text-emerald-600 dark:text-emerald-400">■ Hit</span>
                    <span className="text-destructive">■ Miss</span>
                    <span className="ml-auto">Overall: {overallHitRate}%</span>
                  </div>
                </>
              ) : (
                <>
                  {cacheHistoryEntries.map((entry) => (
                    <div key={entry.runId} title={`Run #${entry.runId}: ${entry.bytecodeCacheSize} bytecode entries`} className="grid grid-cols-[3rem_1fr_2.5rem] items-center gap-2 text-[10px]">
                      <span className="text-muted-foreground font-mono">#{entry.runId}</span>
                      <div className="bg-muted h-3 overflow-hidden rounded-sm">
                        <div className="bg-primary/60 h-full" style={{ width: `${bytecodeBarPct(entry)}%` }} />
                      </div>
                      <span className="text-muted-foreground text-right">{entry.bytecodeCacheSize}</span>
                    </div>
                  ))}
                  <div className="text-muted-foreground pt-1 text-[9px]">
                    Max: {maxBytecodeSize} · Now: {cache.bytecode.length}
                  </div>
                </>
              )}
            </div>
          </div>
        )}

        <div className="rounded-md border">
          <div className="bg-muted/50 flex items-center gap-2 border-b px-3 py-1.5">
            <span className="flex items-center gap-1.5 text-sm font-medium">
              <Table className="size-3.5" /> Line Cache
            </span>
            <span className="text-muted-foreground ml-auto text-xs">
              {cache.lineCache.length} entries · {resolvedLineCount} resolved
            </span>
          </div>
          {cache.lineCache.length === 0 ? (
            <div className="text-muted-foreground p-3 text-center text-sm">No line cache entries</div>
          ) : (
            <div className="p-1">
              {cache.lineCache.map((entry) => (
                <div key={entry.key} className="hover:bg-muted/50 flex flex-wrap items-center gap-2 rounded-sm px-2 py-1 font-mono text-xs">
                  <span className="text-muted-foreground w-8 shrink-0">L{entry.lineNumber}</span>
                  <span className="min-w-0 flex-1 truncate">{entry.resultValue}</span>
                  <span className="text-muted-foreground shrink-0 text-[10px]">{entry.resultType}</span>
                  {entry.reads.length > 0 && (
                    <span className="flex flex-wrap gap-1">
                      {entry.reads.map((r) => (
                        <span key={r} className="bg-muted rounded px-1 text-[10px]">
                          {r}
                        </span>
                      ))}
                    </span>
                  )}
                  {entry.writeVar && <span className="bg-muted rounded px-1 text-[10px]">→ {entry.writeVar}</span>}
                </div>
              ))}
            </div>
          )}
        </div>
      </div>

      {/* Async Data */}
      {(queryCacheEntries.length > 0 || asyncCacheEntries.length > 0) && (
        <div className="space-y-3">
          <div className="text-muted-foreground text-[10px] font-semibold tracking-wide uppercase">Async Data</div>

          {asyncCacheEntries.length > 0 && (
            <div className="rounded-md border">
              <div className="bg-muted/50 flex items-center gap-2 border-b px-3 py-1.5">
                <span className="flex items-center gap-1.5 text-sm font-medium">
                  <Radio className="size-3.5" /> Async Resolver Cache
                </span>
                <span className="text-muted-foreground ml-auto text-xs">
                  {asyncCacheEntries.length} package{asyncCacheEntries.length !== 1 ? "s" : ""}
                </span>
              </div>
              <div className="divide-y">
                {asyncCacheEntries.map((pkg) => (
                  <div key={pkg.packageId} className="flex flex-col gap-1 p-2">
                    <div className="flex flex-wrap items-center gap-2 text-xs">
                      <span className="font-mono font-semibold">{pkg.packageId}</span>
                      <span className="text-emerald-600 dark:text-emerald-400">{pkg.resolvedCount} resolved</span>
                      <span className="text-amber-600 dark:text-amber-400">{pkg.inFlightCount} in-flight</span>
                      <span className={pkg.errorCount > 0 ? "text-destructive" : "text-muted-foreground"}>
                        {pkg.errorCount} error{pkg.errorCount !== 1 ? "s" : ""}
                      </span>
                      {pkg.ttlMs && <span className="text-muted-foreground ml-auto">TTL {formatDuration(pkg.ttlMs)}</span>}
                    </div>
                    {pkg.entries.length > 0 && (
                      <div className="flex flex-wrap gap-1">
                        {pkg.entries.slice(0, 12).map((e) => (
                          <span
                            key={e.key}
                            title={e.status + (e.errorMessage ? `: ${e.errorMessage}` : "")}
                            className={cn(
                              "rounded px-1.5 py-0.5 font-mono text-[10px]",
                              e.status === "error" ? "bg-destructive/10 text-destructive" : e.status === "in_flight" ? "bg-amber-500/10 text-amber-600 dark:text-amber-400" : "bg-muted",
                            )}
                          >
                            {e.key}
                          </span>
                        ))}
                        {pkg.entries.length > 12 && <span className="text-muted-foreground text-[10px]">+{pkg.entries.length - 12} more</span>}
                      </div>
                    )}
                  </div>
                ))}
              </div>
            </div>
          )}

          {queryCacheEntries.length > 0 && (
            <div className="rounded-md border">
              <div className="bg-muted/50 flex items-center gap-2 border-b px-3 py-1.5">
                <span className="flex items-center gap-1.5 text-sm font-medium">
                  <CloudCog className="size-3.5" /> Query Cache (TanStack)
                </span>
                <span className="text-muted-foreground ml-auto text-xs">
                  {queryCacheEntries.length} entries · {queryCacheFreshCount} fresh · {queryCacheStaleCount} stale
                </span>
              </div>
              <div className="divide-y">
                {queryCacheEntries.map((entry) => {
                  const expanded = !!expandedKeys[entry.queryKey]
                  return (
                    <div key={entry.queryKey}>
                      <div onClick={() => toggleExpand(entry.queryKey)} className="hover:bg-muted/50 flex cursor-pointer items-center gap-2 px-3 py-1.5">
                        {expanded ? <ChevronDown className="size-3.5" /> : <ChevronRight className="size-3.5" />}
                        <span title={entry.queryKeyArray.join(" / ")} className="min-w-0 flex-1 truncate font-mono text-xs">
                          {entry.queryKey}
                        </span>
                        <span
                          className={cn(
                            "rounded px-1.5 py-0.5 text-[9px] font-semibold uppercase",
                            entry.status === "fresh" && "bg-emerald-500/10 text-emerald-600 dark:text-emerald-400",
                            entry.status === "stale" && "bg-amber-500/10 text-amber-600 dark:text-amber-400",
                            entry.status === "fetching" && "bg-blue-500/10 text-blue-600 dark:text-blue-400",
                            entry.status === "error" && "bg-destructive/10 text-destructive",
                          )}
                        >
                          {entry.status}
                        </span>
                        <span className="text-muted-foreground text-[10px]">{entry.dataType}</span>
                        <span title={new Date(entry.updatedAt).toLocaleTimeString()} className="text-muted-foreground text-[10px]">
                          {formatAge(entry.updatedAt, nowMs)}
                        </span>
                        <div className="bg-muted h-1.5 w-16 overflow-hidden rounded-full" title={freshnessBarTitle(entry, nowMs)}>
                          <div className={cn("h-full", freshnessBarClass(entry, nowMs))} style={{ width: `${freshnessPct(entry, nowMs)}%` }} />
                        </div>
                      </div>
                      {expanded && (
                        <div className="bg-muted/20 space-y-1.5 px-3 py-2 text-xs">
                          <DetailRow label="Query Key">
                            <span className="flex flex-wrap gap-1">
                              {entry.queryKeyArray.map((seg, i) => (
                                <span key={i} className="bg-muted rounded px-1.5 py-0.5 font-mono text-[10px]">
                                  {seg}
                                </span>
                              ))}
                            </span>
                          </DetailRow>
                          <DetailRow label="Cached Data">
                            <span className="truncate font-mono">{entry.dataPreview}</span>
                          </DetailRow>
                          <DetailRow label="Data Type">{entry.dataType}</DetailRow>
                          <DetailRow label="Status">{entry.status}</DetailRow>
                          <DetailRow label="Freshness">
                            <div className="w-full">
                              <div className="bg-muted h-2 overflow-hidden rounded-full">
                                <div className={cn("h-full", freshnessBarClass(entry, nowMs))} style={{ width: `${freshnessPct(entry, nowMs)}%` }} />
                              </div>
                              <div className="text-muted-foreground mt-0.5 text-[10px]">{freshnessBarTitle(entry, nowMs)}</div>
                            </div>
                          </DetailRow>
                          <DetailRow label="Age">{formatAge(entry.updatedAt, nowMs)}</DetailRow>
                          <DetailRow label="Last Updated">{new Date(entry.updatedAt).toLocaleString()}</DetailRow>
                          <DetailRow label="Stale Time">{formatDuration(entry.staleTime)}</DetailRow>
                          <DetailRow label="Cache Time">
                            {formatDuration(entry.cacheTime)}
                            {entry.cacheTime === Infinity ? " (never evicted)" : ""}
                          </DetailRow>
                        </div>
                      )}
                    </div>
                  )
                })}
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  )
}

function DetailRow({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div className="grid grid-cols-[8rem_1fr] items-start gap-2">
      <span className="text-muted-foreground text-[10px] font-medium uppercase">{label}</span>
      <span>{children}</span>
    </div>
  )
}

// playground/src/components/CacheTab.vue
<template>
  <div class="tab-panel active" id="panel-cache">
    <div class="panel-scroll diag-stack" id="cache-display">
      <empty-state v-if="!cache" icon="database" text="No cache data" hint="Evaluate an expression to see cache diagnostics." />
      <template v-else>
        <!-- Page Cache -->
        <div class="diag-group" v-if="heatmapEntries.length > 0">
          <div class="diag-group-label">Page Cache</div>
          <div class="cache-section">
            <div class="cache-section-header">
              <span class="msi msi-dense">grid_view</span> Page Heatmap
              <span class="cache-section-count">{{ heatmapEntries.length }} pages · 128 lines/page</span>
              <span v-if="preloadDirection" class="preload-direction-badge" :class="'preload-' + preloadDirection" :title="preloadDirectionTitle">
                <span class="msi msi-dense">{{ preloadDirection === 'forward' ? 'trending_up' : preloadDirection === 'backward' ? 'trending_down' : 'trending_flat' }}</span> {{ preloadDirection }} (recent trend)
              </span>
            </div>
            <div class="page-heatmap-grid">
              <div
                v-for="page in heatmapEntries"
                :key="page.pageNum"
                class="page-heatmap-cell"
                :class="'page-heatmap-' + page.temperature"
                :title="'Page ' + page.pageNum + ' (L' + page.startLine + '-' + page.endLine + ')\nTemp: ' + page.temperature + '\nAccess: #' + page.accessSeq"
              >
                <span class="page-heatmap-page-num">{{ page.pageNum }}</span>
                <span class="page-heatmap-range">{{ page.startLine }}–{{ page.endLine }}</span>
              </div>
            </div>
            <div class="page-heatmap-legend">
              <span class="page-heatmap-legend-item page-heatmap-hot">● Hot</span>
              <span class="page-heatmap-legend-item page-heatmap-warm">● Warm</span>
              <span class="page-heatmap-legend-item page-heatmap-cold">● Cold</span>
              <span style="font-size:9px;color:var(--text-muted);margin-left:8px">
                Hot = viewport ±3 pages · Warm = viewport ±6 pages · Cold = beyond
              </span>
            </div>
          </div>
        </div>

        <!-- Bytecode & Line Cache -->
        <div class="diag-group">
          <div class="diag-group-label">Bytecode &amp; Line Cache</div>

          <div class="cache-section">
            <div class="cache-section-header">
              <span class="msi msi-dense">data_object</span> Bytecode Cache
              <span class="cache-section-count">{{ cache.bytecode.length }} entries</span>
            </div>
            <div v-if="cache.bytecode.length === 0" class="cache-entry">
              <span class="empty" style="padding:8px;display:block;width:100%;text-align:center">No bytecode cache entries</span>
            </div>
            <template v-else>
              <div class="diag-legend" style="margin: 8px 10px;">op = opcodes, num = numeric constants, str = string constants; async = contains an async-resolved data source.</div>
              <div v-for="entry in cache.bytecode" :key="entry.expression" class="cache-entry">
                <span class="cache-entry-expr">{{ entry.expression }}</span>
                <span class="cache-entry-meta">{{ entry.opcodesLength }} op · {{ entry.numbersLength }} num · {{ entry.stringsLength }} str{{ entry.hasAsync ? ' · async' : '' }}</span>
              </div>
            </template>
          </div>

          <!-- Cache Trends (merged hit/miss + size trend, toggled) -->
          <div class="cache-section" v-if="cacheHistoryEntries.length > 1">
            <div class="cache-section-header">
              <span class="msi msi-dense">bar_chart</span> Cache Trends
              <span class="cache-section-count">Last {{ cacheHistoryEntries.length }} runs</span>
              <div class="cache-trend-toggle">
                <button :class="{ active: trendView === 'hitmiss' }" @click="trendView = 'hitmiss'">Hit/Miss</button>
                <button :class="{ active: trendView === 'size' }" @click="trendView = 'size'">Size</button>
              </div>
            </div>
            <template v-if="trendView === 'hitmiss'">
              <div class="cache-chart">
                <div
                  v-for="entry in cacheHistoryEntries"
                  :key="entry.runId"
                  class="cache-chart-row"
                  :title="'Run #' + entry.runId + ': ' + entry.cacheHits + ' hits / ' + entry.cacheMisses + ' misses = ' + hitRatePct(entry) + '% hit rate'"
                >
                  <span class="cache-chart-label">#{{ entry.runId }}</span>
                  <div class="cache-chart-bar">
                    <div class="cache-chart-hit" :style="{ width: hitBarPct(entry) + '%' }">{{ entry.cacheHits || '' }}</div>
                    <div class="cache-chart-miss" :style="{ width: missBarPct(entry) + '%' }">{{ entry.cacheMisses || '' }}</div>
                  </div>
                  <span class="cache-chart-pct">{{ hitRatePct(entry) }}%</span>
                </div>
              </div>
              <div class="cache-chart-legend">
                <span class="cache-chart-legend-item hit">■ Hit</span>
                <span class="cache-chart-legend-item miss">■ Miss</span>
                <span style="margin-left:auto;color:var(--text-muted);font-size:9px">Overall: {{ overallHitRate }}%</span>
              </div>
            </template>
            <template v-else>
              <div class="cache-chart">
                <div
                  v-for="entry in cacheHistoryEntries"
                  :key="entry.runId"
                  class="cache-chart-row"
                  :title="'Run #' + entry.runId + ': ' + entry.bytecodeCacheSize + ' bytecode entries'"
                >
                  <span class="cache-chart-label">#{{ entry.runId }}</span>
                  <div class="cache-chart-bar" style="position:relative">
                    <div class="cache-chart-size-bar" :style="{ width: bytecodeBarPct(entry) + '%' }"></div>
                  </div>
                  <span class="cache-chart-pct">{{ entry.bytecodeCacheSize }}</span>
                </div>
              </div>
              <div class="cache-chart-legend">
                <span style="color:var(--text-muted);font-size:9px">Max: {{ maxBytecodeSize }} · Now: {{ cache.bytecode.length }}</span>
              </div>
            </template>
          </div>

          <div class="cache-section">
            <div class="cache-section-header">
              <span class="msi msi-dense">table_rows</span> Line Cache
              <span class="cache-section-count">{{ cache.lineCache.length }} entries · {{ resolvedLineCount }} resolved</span>
            </div>
            <div v-if="cache.lineCache.length === 0" class="cache-entry">
              <span class="empty" style="padding:8px;display:block;width:100%;text-align:center">No line cache entries</span>
            </div>
            <div v-for="entry in cache.lineCache" :key="entry.key" class="cache-entry">
              <span class="cache-entry-key">L{{ entry.lineNumber }}</span>
              <span class="cache-entry-expr">{{ entry.resultValue }}</span>
              <span class="cache-entry-meta">{{ entry.resultType }}</span>
              <span v-if="entry.reads.length > 0" class="cache-entry-reads">
                <span v-for="r in entry.reads" :key="r" class="cache-read-chip">{{ r }}</span>
              </span>
              <span v-if="entry.writeVar" class="cache-entry-reads">
                <span class="cache-read-chip">→ {{ entry.writeVar }}</span>
              </span>
            </div>
          </div>
        </div>

        <!-- Async Data -->
        <div class="diag-group" v-if="queryCacheEntries.length > 0 || asyncCacheEntries.length > 0">
          <div class="diag-group-label">Async Data</div>

          <!-- Async Resolver Cache — per-package resolved/in-flight/error
               counts. Fully populated by the engine but previously never
               rendered anywhere in the playground. -->
          <div class="cache-section" v-if="asyncCacheEntries.length > 0">
            <div class="cache-section-header">
              <span class="msi msi-dense">sensors</span> Async Resolver Cache
              <span class="cache-section-count">{{ asyncCacheEntries.length }} package{{ asyncCacheEntries.length !== 1 ? 's' : '' }}</span>
            </div>
            <div v-for="pkg in asyncCacheEntries" :key="pkg.packageId" class="cache-entry" style="flex-direction: column; align-items: flex-start; gap: 4px;">
              <div style="display:flex; align-items:center; gap: 8px; width: 100%;">
                <span class="cache-entry-key">{{ pkg.packageId }}</span>
                <span class="cache-entry-meta" style="color: var(--success)">{{ pkg.resolvedCount }} resolved</span>
                <span class="cache-entry-meta" style="color: var(--stage-vm)">{{ pkg.inFlightCount }} in-flight</span>
                <span class="cache-entry-meta" :style="{ color: pkg.errorCount > 0 ? 'var(--error)' : 'var(--text-muted)' }">{{ pkg.errorCount }} error{{ pkg.errorCount !== 1 ? 's' : '' }}</span>
                <span v-if="pkg.ttlMs" class="cache-entry-meta" style="margin-left:auto">TTL {{ formatDuration(pkg.ttlMs) }}</span>
              </div>
              <div v-if="pkg.entries.length > 0" class="cache-entry-reads">
                <span
                  v-for="e in pkg.entries.slice(0, 12)"
                  :key="e.key"
                  class="cache-read-chip"
                  :class="{ 'async-entry-error': e.status === 'error', 'async-entry-inflight': e.status === 'in_flight' }"
                  :title="e.status + (e.errorMessage ? ': ' + e.errorMessage : '')"
                >{{ e.key }}</span>
                <span v-if="pkg.entries.length > 12" class="cache-entry-meta">+{{ pkg.entries.length - 12 }} more</span>
              </div>
            </div>
          </div>

          <!-- TanStack Query Cache — expandable entries with freshness bars -->
          <div class="cache-section" v-if="queryCacheEntries.length > 0">
            <div class="cache-section-header">
              <span class="msi msi-dense">cloud_sync</span> Query Cache (TanStack)
              <span class="cache-section-count">{{ queryCacheEntries.length }} entries · {{ queryCacheFreshCount }} fresh · {{ queryCacheStaleCount }} stale</span>
            </div>
            <div
              v-for="entry in queryCacheEntries"
              :key="entry.queryKey"
              class="qc-entry"
              :class="{ 'qc-entry-expanded': isExpanded(entry.queryKey) }"
            >
              <div class="qc-entry-header" @click="toggleExpand(entry.queryKey)">
                <span class="msi msi-dense qc-entry-chevron">{{ isExpanded(entry.queryKey) ? 'expand_more' : 'chevron_right' }}</span>
                <span class="qc-entry-key" :title="entry.queryKeyArray.join(' / ')">{{ entry.queryKey }}</span>
                <span class="qc-entry-status cache-entry-status" :class="'query-' + entry.status">{{ entry.status }}</span>
                <span class="qc-entry-type">{{ entry.dataType }}</span>
                <span class="qc-entry-age" :title="new Date(entry.updatedAt).toLocaleTimeString()">{{ formatAge(entry.updatedAt, nowMs) }}</span>
                <div class="qc-freshness-bar qc-freshness-mini" :class="freshnessBarClass(entry, nowMs)" :title="freshnessBarTitle(entry, nowMs)">
                  <div class="qc-freshness-fill" :style="{ width: freshnessPct(entry, nowMs) + '%' }"></div>
                </div>
              </div>
              <div v-if="isExpanded(entry.queryKey)" class="qc-entry-body">
                <div class="qc-detail-grid">
                  <div class="qc-detail-row">
                    <span class="qc-detail-label">Query Key</span>
                    <span class="qc-detail-chips">
                      <span v-for="(seg, i) in entry.queryKeyArray" :key="i" class="qc-key-chip">{{ seg }}</span>
                    </span>
                  </div>
                  <div class="qc-detail-row">
                    <span class="qc-detail-label">Cached Data</span>
                    <span class="qc-detail-value qc-data-preview">{{ entry.dataPreview }}</span>
                  </div>
                  <div class="qc-detail-row">
                    <span class="qc-detail-label">Data Type</span>
                    <span class="qc-detail-value">{{ entry.dataType }}</span>
                  </div>
                  <div class="qc-detail-row">
                    <span class="qc-detail-label">Status</span>
                    <span class="qc-detail-value cache-entry-status" :class="'query-' + entry.status">{{ entry.status }}</span>
                  </div>
                  <div class="qc-detail-row">
                    <span class="qc-detail-label">Freshness</span>
                    <div class="qc-detail-value" style="width:100%">
                      <div class="qc-freshness-bar qc-freshness-full" :class="freshnessBarClass(entry, nowMs)">
                        <div class="qc-freshness-fill" :style="{ width: freshnessPct(entry, nowMs) + '%' }"></div>
                      </div>
                      <div class="qc-freshness-text">{{ freshnessBarTitle(entry, nowMs) }}</div>
                    </div>
                  </div>
                  <div class="qc-detail-row">
                    <span class="qc-detail-label">Age</span>
                    <span class="qc-detail-value">{{ formatAge(entry.updatedAt, nowMs) }}</span>
                  </div>
                  <div class="qc-detail-row">
                    <span class="qc-detail-label">Last Updated</span>
                    <span class="qc-detail-value">{{ new Date(entry.updatedAt).toLocaleString() }}</span>
                  </div>
                  <div class="qc-detail-row">
                    <span class="qc-detail-label">Stale Time</span>
                    <span class="qc-detail-value">{{ formatDuration(entry.staleTime) }}</span>
                  </div>
                  <div class="qc-detail-row">
                    <span class="qc-detail-label">Cache Time</span>
                    <span class="qc-detail-value">{{ formatDuration(entry.cacheTime) }}{{ entry.cacheTime === Infinity ? ' (never evicted)' : '' }}</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </template>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue';
import { useNow } from '@vueuse/core';
import { useDiagnosticReportStore } from '../stores/diagnosticReport.js';
import type { CacheHistoryEntry } from '../stores/diagnosticReport.js';
import type { PageHeatmapEntry, QueryCacheEntry } from '@bridge/engine';
import { formatDuration } from '@bridge/utils';
import EmptyState from './shared/EmptyState.vue';

const dr = useDiagnosticReportStore();
const nowDate = useNow({ interval: 1000 });
const nowMs = computed(() => nowDate.value.getTime());

const cache = computed(() => dr.cacheSnapshot);

const resolvedLineCount = computed(() =>
  (cache.value?.lineCache ?? []).filter(e => e.resultType !== 'Pending').length,
);

const heatmapEntries = computed<PageHeatmapEntry[]>(() => dr.pageHeatmap);
const asyncCacheEntries = computed(() => cache.value?.asyncCache ?? []);

/** Query cache entries from TanStack Query. */
const queryCacheEntries = computed<QueryCacheEntry[]>(() => dr.queryCache);
const queryCacheFreshCount = computed(() => queryCacheEntries.value.filter(e => e.status === 'fresh').length);
const queryCacheStaleCount = computed(() => queryCacheEntries.value.filter(e => e.status === 'stale').length);

// ── Cache Trend Chart (toggled between hit/miss and size views) ────────
const trendView = ref<'hitmiss' | 'size'>('hitmiss');

/** Per-evaluation cache metrics history. */
const cacheHistoryEntries = computed<CacheHistoryEntry[]>(() => dr.cacheHistory);

/** Overall hit rate across all tracked runs (0–100). */
const overallHitRate = computed(() => {
  const entries = cacheHistoryEntries.value;
  if (entries.length === 0) return 0;
  let totalHits = 0;
  let totalLines = 0;
  for (const e of entries) {
    totalHits += e.cacheHits;
    totalLines += e.cacheHits + e.cacheMisses;
  }
  return totalLines > 0 ? Math.round((totalHits / totalLines) * 100) : 0;
});

/** Max bar width reference value for hit/miss bars (largest total lines in any run). */
const maxHitMissTotal = computed(() => {
  let max = 0;
  for (const e of cacheHistoryEntries.value) {
    const total = e.cacheHits + e.cacheMisses;
    if (total > max) max = total;
  }
  return max;
});

/** Hit rate percentage for a single entry. */
function hitRatePct(entry: CacheHistoryEntry): number {
  const total = entry.cacheHits + entry.cacheMisses;
  return total > 0 ? Math.round((entry.cacheHits / total) * 100) : 0;
}

/** Bar width percentage for the hits portion (relative to max across runs). */
function hitBarPct(entry: CacheHistoryEntry): number {
  if (maxHitMissTotal.value === 0) return 0;
  return Math.round((entry.cacheHits / maxHitMissTotal.value) * 100);
}

/** Bar width percentage for the misses portion (relative to max across runs). */
function missBarPct(entry: CacheHistoryEntry): number {
  if (maxHitMissTotal.value === 0) return 0;
  return Math.round((entry.cacheMisses / maxHitMissTotal.value) * 100);
}

/** Max bytecode cache size across all tracked runs (for bar scaling). */
const maxBytecodeSize = computed(() => {
  let max = 0;
  for (const e of cacheHistoryEntries.value) {
    if (e.bytecodeCacheSize > max) max = e.bytecodeCacheSize;
  }
  return max;
});

/** Bar width percentage for bytecode cache size (relative to max across runs). */
function bytecodeBarPct(entry: CacheHistoryEntry): number {
  if (maxBytecodeSize.value === 0) return 0;
  return Math.round((entry.bytecodeCacheSize / maxBytecodeSize.value) * 100);
}

// ── Expand/collapse state ──────────────────────────────────────────────
const expandedKeys = ref<Record<string, boolean>>({});

function isExpanded(key: string): boolean {
  return !!expandedKeys.value[key];
}

function toggleExpand(key: string): void {
  expandedKeys.value[key] = !expandedKeys.value[key];
}

// ── Freshness progress bar ─────────────────────────────────────────────

/** Percentage of staleTime elapsed since updatedAt. 0% = just updated, 100% = fully stale. */
function freshnessPct(entry: QueryCacheEntry, nowMs: number): number {
  if (!entry.staleTime || entry.staleTime <= 0) return 0;
  const elapsed = nowMs - entry.updatedAt;
  return Math.min(100, Math.max(0, (elapsed / entry.staleTime) * 100));
}

/** CSS class for the freshness bar: ttl-fresh (green), ttl-warning (amber), ttl-expiring (red). */
function freshnessBarClass(entry: QueryCacheEntry, nowMs: number): string {
  if (!entry.staleTime || entry.staleTime <= 0) return 'ttl-fresh';
  const pct = freshnessPct(entry, nowMs);
  if (pct < 50) return 'ttl-fresh';
  if (pct < 90) return 'ttl-warning';
  return 'ttl-expiring';
}

/** Tooltip text for the freshness bar. */
function freshnessBarTitle(entry: QueryCacheEntry, nowMs: number): string {
  if (!entry.staleTime || entry.staleTime <= 0) return 'Never stale';
  const elapsed = nowMs - entry.updatedAt;
  const remaining = Math.max(0, entry.staleTime - elapsed);
  if (remaining <= 0) return 'Stale — data may be refetched on next access';
  const sec = Math.floor(remaining / 1000);
  if (sec < 60) return `${sec}s until stale`;
  const min = Math.floor(sec / 60);
  if (min < 60) return `${min}m until stale`;
  return `${Math.floor(min / 60)}h until stale`;
}

// ── Formatting helpers ─────────────────────────────────────────────────

/** Format an epoch-ms timestamp as a human-readable age (e.g., "12s", "3m", "1h"). */
function formatAge(createdAt: number, nowMs: number): string {
  const diffMs = nowMs - createdAt;
  if (diffMs < 0) return 'just now';
  const sec = Math.floor(diffMs / 1000);
  if (sec < 60) return `${sec}s`;
  const min = Math.floor(sec / 60);
  if (min < 60) return `${min}m`;
  const hrs = Math.floor(min / 60);
  return `${hrs}h`;
}

/* Preload direction: compute by examining access sequence number trend across pages.
 * If pages with higher accessSeq are at higher page indices → forward.
 * If pages with higher accessSeq are at lower page indices → backward.
 * Otherwise → stable. Labeled "(recent trend)" in the template since this
 * is a derived heuristic over a normalized access-order value, not a
 * hard guarantee about future preload behavior. */
const preloadDirection = computed<string | null>(() => {
  const entries = heatmapEntries.value;
  if (entries.length < 2) return null;
  const trend = entries.reduce((acc, entry, i) => {
    if (i === 0) return 0;
    const diff = entry.accessSeq - entries[i - 1].accessSeq;
    return acc + (diff > 0 ? 1 : diff < 0 ? -1 : 0);
  }, 0);
  if (trend > 0) return 'forward';
  if (trend < 0) return 'backward';
  return 'stable';
});

const preloadDirectionTitle = computed<string>(() => {
  const dir = preloadDirection.value;
  if (dir === 'forward') return 'Heuristic: recently-accessed pages trend toward higher page numbers';
  if (dir === 'backward') return 'Heuristic: recently-accessed pages trend toward lower page numbers';
  if (dir === 'stable') return 'Heuristic: no clear directional trend in recent page access';
  return '';
});
</script>
