// webapp/src/components/ExamplesMenu.tsx
import { useEffect, useMemo, useRef, useState } from "react"
import { BookOpen, ChevronDown, ChevronUp } from "lucide-react"
import { exampleData, fullDocumentExamples } from "@bridge/examples"
import { useEditorStore } from "@/stores/editor"
import { useClickOutside } from "@/hooks/useClickOutside"
import { Input } from "@/components/ui/input"
import { ExampleCategory } from "@/components/ExampleCategory"
import { cn } from "@/lib/utils"

/** Searchable example/template picker. Ported from playground's ExamplesMenu.vue + ExampleCategory.vue. */
export function ExamplesMenu() {
  const insertExample = useEditorStore((s) => s.insertExample)
  const [open, setOpen] = useState(false)
  const [filterQuery, setFilterQuery] = useState("")
  const rootRef = useRef<HTMLDivElement>(null)
  const filterInputRef = useRef<HTMLInputElement>(null)

  useClickOutside(rootRef, () => setOpen(false), open)

  useEffect(() => {
    if (open) {
      requestAnimationFrame(() => filterInputRef.current?.focus())
    } else {
      setFilterQuery("")
    }
  }, [open])

  const totalExampleCount = useMemo(() => exampleData.reduce((n, c) => n + c.examples.length, 0), [])

  const filteredCategories = useMemo(() => {
    const q = filterQuery.trim().toLowerCase()
    if (!q) return exampleData
    return exampleData
      .map((cat) => ({
        ...cat,
        examples: cat.examples.filter(
          (ex) =>
            ex.name.toLowerCase().includes(q) ||
            ex.expression.toLowerCase().includes(q) ||
            ex.description.toLowerCase().includes(q),
        ),
      }))
      .filter((cat) => cat.examples.length > 0)
  }, [filterQuery])

  function onSelect(expression: string) {
    insertExample(expression)
    setOpen(false)
  }

  function onFullDocSelect(e: React.ChangeEvent<HTMLSelectElement>) {
    const value = e.target.value
    if (value) {
      insertExample(value)
      e.target.value = ""
      setOpen(false)
    }
  }

  return (
    <div ref={rootRef} className="relative">
      <button
        type="button"
        onClick={() => setOpen((o) => !o)}
        className={cn(
          "flex items-center gap-1.5 rounded-md border px-2.5 py-1 text-xs transition-colors",
          open ? "border-primary/30 bg-accent text-accent-foreground" : "text-muted-foreground hover:bg-accent hover:text-accent-foreground",
        )}
      >
        <BookOpen className="size-3.5" />
        Examples
        <span className="bg-muted rounded px-1 text-[10px] tabular-nums">{totalExampleCount}</span>
        {open ? <ChevronUp className="size-3.5" /> : <ChevronDown className="size-3.5" />}
      </button>

      {open && (
        <div className="bg-popover border-border/80 absolute top-full right-0 z-30 mt-1.5 flex max-h-[70vh] w-80 flex-col gap-2 overflow-hidden rounded-lg border p-2 shadow-2xl">
          <div className="flex gap-1.5">
            <Input
              ref={filterInputRef}
              value={filterQuery}
              onChange={(e) => setFilterQuery(e.target.value)}
              placeholder="Filter examples…"
              spellCheck={false}
              className="h-8"
            />
            <select
              onChange={onFullDocSelect}
              defaultValue=""
              className="border-input bg-background h-8 rounded-md border px-2 text-xs"
            >
              <option value="">Full Documents…</option>
              {fullDocumentExamples.map((doc) => (
                <option key={doc.name} value={doc.content}>
                  {doc.name}
                </option>
              ))}
            </select>
          </div>
          <div className="flex flex-col gap-1 overflow-y-auto">
            {filterQuery && filteredCategories.length === 0 && (
              <div className="text-muted-foreground p-2 text-center text-sm">
                No examples match &ldquo;{filterQuery}&rdquo;
              </div>
            )}
            {filteredCategories.map((cat) => (
              <ExampleCategory key={cat.name} category={cat} forceExpanded={filterQuery.length > 0} onSelect={onSelect} />
            ))}
          </div>
        </div>
      )}
    </div>
  )
}

// playground/src/components/ExamplesMenu.vue
<template>
  <div class="examples-menu" v-click-outside="close">
    <button class="examples-menu-trigger" :class="{ open }" @click="open = !open">
      <span class="msi msi-dense">menu_book</span> Examples <span class="examples-menu-count">{{ totalExampleCount }}</span>
      <span class="msi msi-dense examples-menu-chevron">{{ open ? 'expand_less' : 'expand_more' }}</span>
    </button>

    <div v-if="open" class="examples-menu-panel">
      <div class="examples-menu-filter-row">
        <input
          ref="filterInputRef"
          type="text"
          class="sidebar-filter-input"
          placeholder="Filter examples…"
          spellcheck="false"
          v-model="filterQuery"
        />
        <select class="full-doc-select" @change="onFullDocSelect">
          <option value="">Full Documents…</option>
          <option v-for="doc in fullDocumentExamples" :key="doc.name" :value="doc.content">
            {{ doc.name }}
          </option>
        </select>
      </div>
      <div class="examples-menu-list">
        <div v-if="filterQuery && filteredCategories.length === 0" class="sidebar-no-matches">No examples match &ldquo;{{ filterQuery }}&rdquo;</div>
        <ExampleCategory
          v-for="cat in filteredCategories"
          :key="cat.name"
          :category="cat"
          :force-expanded="filterQuery.length > 0"
          @select="onExampleSelect"
        />
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, nextTick, ref, watch, type Directive } from 'vue';
import { useEditorStore } from '../stores/editor.js';
import { exampleData, fullDocumentExamples } from '@bridge/examples';
import ExampleCategory from './ExampleCategory.vue';

const editor = useEditorStore();

const open = ref(false);
const filterQuery = ref('');
const filterInputRef = ref<HTMLInputElement | null>(null);

const totalExampleCount = computed(() => exampleData.reduce((n, c) => n + c.examples.length, 0));

const filteredCategories = computed(() => {
  const q = filterQuery.value.trim().toLowerCase();
  if (!q) return exampleData;
  return exampleData
    .map(cat => ({
      ...cat,
      examples: cat.examples.filter(ex =>
        ex.name.toLowerCase().includes(q) ||
        ex.expression.toLowerCase().includes(q) ||
        ex.description.toLowerCase().includes(q),
      ),
    }))
    .filter(cat => cat.examples.length > 0);
});

function close(): void {
  open.value = false;
}

watch(open, (val) => {
  if (val) nextTick(() => filterInputRef.value?.focus());
  else filterQuery.value = '';
});

function onExampleSelect(expression: string): void {
  editor.insertExample(expression);
  close();
}

function onFullDocSelect(e: Event): void {
  const sel = e.target as HTMLSelectElement;
  if (sel.value) {
    editor.insertExample(sel.value);
    sel.value = '';
    close();
  }
}

/** Minimal click-outside directive — closes the dropdown when clicking anywhere else. */
const vClickOutside: Directive<HTMLElement, () => void> = {
  mounted(el, binding) {
    (el as any)._clickOutsideHandler = (e: MouseEvent) => {
      if (!el.contains(e.target as Node)) binding.value();
    };
    document.addEventListener('mousedown', (el as any)._clickOutsideHandler);
  },
  unmounted(el) {
    document.removeEventListener('mousedown', (el as any)._clickOutsideHandler);
  },
};
</script>
