// webapp/src/components/tabs/OutputTab.tsx
import { useMemo } from "react"
import { Copy, Check, AlertTriangle, LoaderCircle } from "lucide-react"
import { useState } from "react"
import type { Token, LineResult } from "@bridge/engine"
import { useDiagnosticReportStore } from "@/stores/diagnosticReport"
import { useTokensStore, matchToken } from "@/stores/tokens"
import { usePipelineStore } from "@/stores/pipeline"
import { Input } from "@/components/ui/input"
import { cn } from "@/lib/utils"

interface GroupEntry {
  line: number
  tokens: Token[]
  result: LineResult | null
}

/** Three-tier badge helpers. */
function getTier(result: LineResult): "tier-1" | "tier-2" | "tier-3" | "tier-skip" {
  if (result.error) return "tier-skip"
  if (result.wasCached) return "tier-2"
  if (result.type === "Pending") return "tier-3"
  return "tier-1"
}

const TIER_CLASS: Record<string, string> = {
  "tier-1": "bg-emerald-500/10 text-emerald-600 dark:text-emerald-400",
  "tier-2": "bg-emerald-500/10 text-emerald-600 dark:text-emerald-400",
  "tier-3": "bg-amber-500/10 text-amber-600 dark:text-amber-400",
  "tier-skip": "bg-destructive/10 text-destructive",
}

function getTierStatusLabel(result: LineResult): string {
  if (result.error) return "Error"
  if (result.wasCached) return "T2 Cached"
  if (result.type === "Pending") return "T3 Pending"
  return "T1 Fresh"
}

function getTierReason(result: LineResult): string {
  if (result.error) return `Error: ${result.error}`
  if (result.wasCached) return "Tier 2 (Cache hit) — bytecode reused from earlier evaluation"
  if (result.type === "Pending") return "Tier 3 (Async pending) — awaiting external data resolution"
  return "Tier 1 (Fresh) — full eval: lexer → parser → compiler → VM"
}

async function copyText(text: string): Promise<void> {
  try {
    await navigator.clipboard.writeText(text)
  } catch {
    const ta = document.createElement("textarea")
    ta.value = text
    ta.style.position = "fixed"
    ta.style.left = "-9999px"
    document.body.appendChild(ta)
    ta.select()
    document.execCommand("copy")
    document.body.removeChild(ta)
  }
}

/**
 * Raw lexer output — either a flat token stream or grouped by line, each
 * group annotated with its evaluated tier/status. Ported from playground's
 * OutputTab.vue.
 */
export function OutputTab() {
  const result = useDiagnosticReportStore((s) => s.result)
  const lineResults = useDiagnosticReportStore((s) => s.lineResults)
  const opcodes = useDiagnosticReportStore((s) => s.opcodes)
  const groupByLine = useTokensStore((s) => s.groupByLine)
  const setGroupByLine = useTokensStore((s) => s.setGroupByLine)
  const filterQuery = useTokensStore((s) => s.filterQuery)
  const setFilterQuery = useTokensStore((s) => s.setFilterQuery)
  const selectedLine = usePipelineStore((s) => s.selectedLine)
  const [copiedResult, setCopiedResult] = useState<string | null>(null)

  const display = useMemo(() => {
    if (!result) {
      return { groupEntries: [] as GroupEntry[], flatTokensList: [] as Token[], countLabel: "0 tokens", visibleCount: 0, filterActive: false }
    }

    const rawTokens = result.rawTokens ?? []
    const hasFilter = filterQuery.length > 0

    const resultByLine = new Map<number, LineResult>()
    for (const lr of result.lineResults ?? []) resultByLine.set(lr.lineNumber ?? 1, lr)

    const filtered: Token[] = []
    for (const t of rawTokens) {
      if (t.type === "WS" || t.type === "NEWLINE") continue
      if (hasFilter && !matchToken(t, filterQuery)) continue
      filtered.push(t)
    }
    const totalCount = filtered.length

    let groupEntries: GroupEntry[] = []
    let flatTokensList: Token[] = []
    let visibleCount = 0

    if (groupByLine) {
      const lineMap = new Map<number, Token[]>()
      const lineOrder: number[] = []
      for (const t of filtered) {
        const ln = t.line ?? 1
        if (!lineMap.has(ln)) {
          lineMap.set(ln, [])
          lineOrder.push(ln)
        }
        lineMap.get(ln)!.push(t)
      }
      lineOrder.sort((a, b) => a - b)
      groupEntries = lineOrder.map((ln) => ({ line: ln, tokens: lineMap.get(ln)!, result: resultByLine.get(ln) ?? null }))
      visibleCount = groupEntries.reduce((sum, e) => sum + e.tokens.length, 0)
    } else {
      flatTokensList = filtered
      visibleCount = filtered.length
    }

    const countLabel = rawTokens.length === 0 ? "0 tokens" : hasFilter ? `${visibleCount} / ${totalCount} tokens` : `${totalCount} tokens`

    return { groupEntries, flatTokensList, countLabel, visibleCount, filterActive: hasFilter }
  }, [result, filterQuery, groupByLine])

  const tierSummary = useMemo(() => {
    const s = { t1: 0, t2: 0, t3: 0, skip: 0, total: lineResults.length }
    for (const r of lineResults) {
      if (r.error) s.skip++
      else if (r.wasCached) s.t2++
      else if (r.type === "Pending") s.t3++
      else s.t1++
    }
    return s
  }, [lineResults])

  const tierTooltips = useMemo(() => {
    const b = { t1: [] as number[], t2: [] as number[], t3: [] as number[], skip: [] as { line: number; error: string; expr: string }[] }
    for (const r of lineResults) {
      const ln = r.lineNumber ?? 1
      if (r.error) b.skip.push({ line: ln, error: r.error, expr: r.expression })
      else if (r.wasCached) b.t2.push(ln)
      else if (r.type === "Pending") b.t3.push(ln)
      else b.t1.push(ln)
    }
    const fmtLines = (nums: number[]) => (nums.length > 0 ? "\nLines: " + nums.join(", ") : "")
    const fmtSkip = b.skip.length > 0 ? "\n" + b.skip.map((s) => `L${s.line} "${s.expr}": ${s.error}`).join("\n") : ""
    return {
      t1: "Fresh — full evaluation (lexer → parser → compiler → VM), nothing reused." + fmtLines(b.t1),
      t2: "Cached — bytecode reused from an earlier evaluation of the same expression." + fmtLines(b.t2),
      t3: "Pending — async data (e.g. a currency/price lookup) hasn't resolved yet." + fmtLines(b.t3),
      skip: "A parse or evaluation error." + fmtSkip,
    }
  }, [lineResults])

  const hasAnyResults = lineResults.some((r) => r.result || r.error)

  function copyAllResults() {
    const text = lineResults.map((r) => `L${r.lineNumber ?? 1}: ${r.expression} = ${r.error ?? r.result ?? ""}`).join("\n")
    if (text) copyText(text)
  }

  function copyResult(text: string) {
    if (!text) return
    copyText(text).then(() => {
      setCopiedResult(text)
      setTimeout(() => setCopiedResult((c) => (c === text ? null : c)), 1000)
    })
  }

  return (
    <div className="flex min-h-0 flex-1 flex-col">
      <div className="flex items-center gap-2 border-b px-4 py-1.5">
        <label className="text-muted-foreground flex items-center gap-1.5 text-xs">
          <input type="checkbox" checked={groupByLine} onChange={(e) => setGroupByLine(e.target.checked)} />
          Group by line
        </label>
        <Input
          value={filterQuery}
          onChange={(e) => setFilterQuery(e.target.value)}
          placeholder="Filter tokens…"
          spellCheck={false}
          className="h-7 max-w-45 text-xs"
        />
        {hasAnyResults && (
          <button
            type="button"
            onClick={copyAllResults}
            title="Copy all line results"
            className="text-muted-foreground hover:bg-accent flex items-center gap-1 rounded-md border px-2 py-1 text-xs"
          >
            <Copy className="size-3.5" /> Copy all
          </button>
        )}
        <span className="text-muted-foreground ml-auto text-xs">{display.countLabel}</span>
      </div>

      {result && tierSummary.total > 0 && (
        <div className="flex flex-wrap items-center gap-1.5 border-b px-4 py-1.5">
          <span className="text-muted-foreground text-[10px] font-medium uppercase">Evaluation Tiers</span>
          <span title={tierTooltips.t1} className="rounded-full bg-emerald-500/10 px-2 py-0.5 text-[10px] font-semibold text-emerald-600 dark:text-emerald-400">
            T1: {tierSummary.t1} fresh
          </span>
          <span title={tierTooltips.t2} className="rounded-full bg-emerald-500/10 px-2 py-0.5 text-[10px] font-semibold text-emerald-600 dark:text-emerald-400">
            T2: {tierSummary.t2} cached
          </span>
          <span
            title={tierTooltips.t3}
            className="flex items-center gap-1 rounded-full bg-amber-500/10 px-2 py-0.5 text-[10px] font-semibold text-amber-600 dark:text-amber-400"
          >
            {tierSummary.t3 > 0 && <LoaderCircle className="size-2.5 animate-spin" />}
            T3: {tierSummary.t3} pending
          </span>
          {tierSummary.skip > 0 && (
            <span title={tierTooltips.skip} className="bg-destructive/10 text-destructive rounded-full px-2 py-0.5 text-[10px] font-semibold">
              SKIP: {tierSummary.skip} errors
            </span>
          )}
        </div>
      )}

      <div className="flex-1 overflow-y-auto p-3">
        {!result ? (
          <div className="text-muted-foreground text-sm">No tokens</div>
        ) : display.visibleCount === 0 ? (
          <div className="text-muted-foreground text-sm">{display.filterActive ? `No tokens match "${filterQuery}"` : "No tokens"}</div>
        ) : groupByLine ? (
          <div className="flex flex-col gap-2">
            {display.groupEntries.map((entry) => (
              <div
                key={entry.line}
                className={cn(
                  "rounded-md border p-2",
                  selectedLine === entry.line && "border-primary",
                  entry.result && getTier(entry.result) === "tier-skip" && "border-destructive/40",
                )}
              >
                <div className="mb-1.5 flex flex-wrap items-center gap-2">
                  <span className="text-sm font-semibold">Line {entry.line}</span>
                  {entry.result && (
                    <span
                      title={getTierReason(entry.result) + (entry.result.wasCached ? " · cache HIT" : " · cache MISS")}
                      className={cn("flex items-center gap-1 rounded-full px-2 py-0.5 text-[10px] font-semibold", TIER_CLASS[getTier(entry.result)])}
                    >
                      {entry.result.type === "Pending" && !entry.result.error && <LoaderCircle className="size-2.5 animate-spin" />}
                      {getTierStatusLabel(entry.result)}
                    </span>
                  )}
                  {entry.result?.parselet && (
                    <span title={`Matched parselet: ${entry.result.parselet}`} className="bg-muted rounded px-1.5 py-0.5 font-mono text-[10px]">
                      {entry.result.parselet}
                    </span>
                  )}
                  <span className="text-muted-foreground ml-auto flex gap-2 font-mono text-[10px]">
                    <span>
                      {entry.tokens.length} token{entry.tokens.length !== 1 ? "s" : ""}
                    </span>
                    <span>
                      {entry.result?.opcodeCount ?? opcodes.length ?? 0} opcode{(entry.result?.opcodeCount ?? 1) !== 1 ? "s" : ""}
                    </span>
                  </span>
                </div>

                <div className="flex flex-wrap items-center gap-1.5">
                  <span className="text-muted-foreground text-[10px] font-medium uppercase">Tokens</span>
                  {entry.tokens.map((t, i) => (
                    <span
                      key={i}
                      title={`Type: ${t.type}\nValue: ${t.value}\nPos: ${t.offset}`}
                      className="bg-muted rounded px-1.5 py-0.5 font-mono text-xs"
                    >
                      {t.value}
                    </span>
                  ))}
                </div>

                {entry.result && (
                  <div className="mt-1.5 flex items-center gap-2 border-t pt-1.5 font-mono text-xs">
                    <span className={cn(entry.result.error ? "text-destructive" : "text-violet-600 dark:text-violet-400")}>{entry.result.type}</span>
                    <span className="text-muted-foreground">→</span>
                    <span className={cn("flex items-center gap-1", entry.result.error ? "text-destructive" : "text-primary")}>
                      {entry.result.type === "Pending" && !entry.result.error && <LoaderCircle className="size-2.5 animate-spin" />}
                      {entry.result.error || entry.result.result || (entry.result.type === "Pending" ? "awaiting resolution…" : "")}
                    </span>
                    {entry.result.timedOut && (
                      <span title="API fetch timed out — result is a 0 gp fallback, not real data" className="flex items-center gap-1 text-amber-600 dark:text-amber-400">
                        <AlertTriangle className="size-3" /> timed out
                      </span>
                    )}
                    <button
                      type="button"
                      onClick={() => copyResult(entry.result!.error || entry.result!.result)}
                      title="Copy result"
                      className="hover:bg-muted ml-auto rounded p-1"
                    >
                      {copiedResult === (entry.result.error || entry.result.result) ? <Check className="size-3" /> : <Copy className="size-3" />}
                    </button>
                  </div>
                )}
              </div>
            ))}
          </div>
        ) : (
          <div className="flex flex-wrap gap-1.5">
            {display.flatTokensList.map((t, i) => (
              <span key={i} title={`Type: ${t.type}\nValue: ${t.value}\nPos: ${t.offset}`} className="bg-muted rounded px-1.5 py-0.5 font-mono text-xs">
                {t.value}
              </span>
            ))}
          </div>
        )}
      </div>
    </div>
  )
}

// playground/src/components/OutputTab.vue
<template>
  <div class="tab-panel active" id="panel-tokens">
    <div class="panel-toolbar">
      <div class="panel-toolbar-left">
        <label class="toggle-label">
          <input type="checkbox" v-model="tokens.groupByLine">
          Group by line
        </label>
        <input
          type="text"
          class="token-filter-input"
          placeholder="Filter tokens…"
          spellcheck="false"
          :value="tokens.filterQuery"
          @input="tokens.setFilterQuery(($event.target as HTMLInputElement).value)"
        />
      </div>
      <button v-if="hasAnyResults" class="copy-all-btn" title="Copy all line results" @click="copyAllResults"><span class="msi msi-dense">content_copy</span> Copy all</button>
      <span class="token-count">{{ countLabel }}</span>
    </div>

    <!-- Three-tier summary bar — each pill's hover tooltip explains what
         the tier means AND which lines are in it, so there's no separate
         legend to open just to learn what "T1"/"T2"/"T3" stand for. -->
    <div v-if="dr.result && tierSummary.total > 0" class="tier-summary-bar">
      <span class="tier-summary-label">Evaluation Tiers</span>
      <span
        class="tier-summary-pill tier-pill-1"
        :title="tierTooltips.t1"
      >T1: {{ tierSummary.t1 }} fresh</span>
      <span
        class="tier-summary-pill tier-pill-2"
        :title="tierTooltips.t2"
      >T2: {{ tierSummary.t2 }} cached</span>
      <span
        class="tier-summary-pill tier-pill-3"
        :title="tierTooltips.t3"
      ><span v-if="tierSummary.t3 > 0" class="msi msi-dense msi-spin microstat-pending-spinner">progress_activity</span>T3: {{ tierSummary.t3 }} pending</span>
      <span
        v-if="tierSummary.skip > 0"
        class="tier-summary-pill tier-pill-skip"
        :title="tierTooltips.skip"
      >SKIP: {{ tierSummary.skip }} errors</span>
    </div>

    <div class="panel-scroll">
      <span v-if="!dr.result" class="empty">No tokens</span>
      <span v-else-if="visibleCount === 0 && filterActive" class="empty">No tokens match &ldquo;{{ tokens.filterQuery }}&rdquo;</span>
      <span v-else-if="visibleCount === 0" class="empty">No tokens</span>

      <template v-else-if="tokens.groupByLine">
        <div
          v-for="entry in groupEntries"
          :key="entry.line"
          class="token-line-group"
          :class="[{ selected: pipeline.selectedLine === entry.line }, entry.result ? 'status-' + getTierClass(entry.result) : '']"
        >
          <div class="token-line-header">
            <div class="token-line-header-left">
              <span class="token-line-header-label">Line {{ entry.line }}</span>
              <!-- Single primary status chip (was: 3 separate badges —
                   tier, cache HIT/MISS, and OK/ERROR/PENDING — competing
                   for attention with no clear hierarchy). Full detail
                   (cache hit/miss, exact reason) stays in the tooltip. -->
              <span
                v-if="entry.result"
                class="status-chip"
                :class="'status-chip-' + getTierClass(entry.result)"
                :title="getTierReason(entry.result) + (entry.result.wasCached ? ' · cache HIT' : ' · cache MISS')"
              >
                <span v-if="entry.result.type === 'Pending' && !entry.result.error" class="msi msi-dense msi-spin microstat-pending-spinner">progress_activity</span>
                {{ getTierStatusLabel(entry.result) }}
              </span>
              <span v-if="entry.result?.parselet" class="parselet-chip" :title="'Matched parselet: ' + entry.result.parselet">{{ entry.result.parselet }}</span>
            </div>
            <div class="token-line-counts">
              <span class="token-count-badge">{{ entry.tokens.length }} token{{ entry.tokens.length !== 1 ? 's' : '' }}</span>
              <span class="opcode-count-badge">{{ entry.result?.opcodeCount ?? dr.opcodes.length ?? 0 }} opcode{{ (entry.result?.opcodeCount ?? 1) !== 1 ? 's' : '' }}</span>
            </div>
          </div>

          <div class="token-line-content">
            <span class="output-label-inline">Tokens</span>
            <span
              v-for="(t, i) in entry.tokens"
              :key="i"
              class="token"
              :class="'token-' + String(t.type || 'unknown').toLowerCase()"
              :title="'Type: ' + t.type + '\\nValue: ' + t.value + '\\nPos: ' + t.offset"
            >{{ t.value }}</span>
          </div>

          <div v-if="entry.result" class="token-line-result">
            <span class="token-line-result-type" :style="{ color: entry.result.error ? 'var(--error)' : 'var(--stage-parser)' }">
              {{ entry.result.type }}
            </span>
            <span class="token-line-result-arrow">→</span>
            <span class="token-line-result-value" :style="{ color: entry.result.error ? 'var(--error)' : 'var(--accent)' }">
              <span v-if="entry.result.type === 'Pending' && !entry.result.error" class="msi msi-dense msi-spin microstat-pending-spinner">progress_activity</span>{{ entry.result.error || entry.result.result || (entry.result.type === 'Pending' ? 'awaiting resolution…' : '') }}
            </span>
            <span v-if="entry.result.timedOut" class="token-line-result-timeout" title="API fetch timed out — result is a 0 gp fallback, not real data">
              <span class="msi msi-dense">warning</span> timed out
            </span>
            <button
              class="token-line-result-copy"
              :data-copy="entry.result.error || entry.result.result"
              title="Copy result"
              @click="copyResult($event)"
            ><span class="msi msi-dense">content_copy</span></button>
          </div>
        </div>
      </template>

      <div v-else class="token-list">
        <span
          v-for="(t, i) in flatTokensList"
          :key="i"
          class="token"
          :class="'token-' + t.type.toLowerCase()"
          :title="'Type: ' + t.type + '\\nValue: ' + t.value + '\\nPos: ' + t.offset"
        >{{ t.value }}</span>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, watch, computed } from 'vue';
import { useDiagnosticReportStore } from '../stores/diagnosticReport.js';
import { useTokensStore } from '../stores/tokens.js';
import { usePipelineStore } from '../stores/pipeline.js';
import type { Token, LineResult } from '../engine.js';

const dr = useDiagnosticReportStore();
const tokens = useTokensStore();
const pipeline = usePipelineStore();

/* ── Reactive display data (updated by watchers) ──────────────── */
interface GroupEntry {
  line: number;
  tokens: Token[];
  result: LineResult | null;
}

const groupEntries = ref<GroupEntry[]>([]);
const flatTokensList = ref<Token[]>([]);
const countLabel = ref('0 tokens');
const visibleCount = ref(0);
const filterActive = ref(false);

function matchToken(t: Token, query: string): boolean {
  if (!query) return true;
  const q = query.toLowerCase();
  return t.value.toLowerCase().includes(q) || t.type.toLowerCase().includes(q);
}

function updateDisplay(): void {
  const result = dr.result;
  if (!result) {
    groupEntries.value = [];
    flatTokensList.value = [];
    countLabel.value = '0 tokens';
    visibleCount.value = 0;
    filterActive.value = false;
    return;
  }

  const rawTokens = result.rawTokens ?? [];
  const query = tokens.filterQuery;
  const hasFilter = query.length > 0;
  filterActive.value = hasFilter;
  const groupByLine = tokens.groupByLine;

  // Build line result lookup
  const resultByLine = new Map<number, LineResult>();
  for (const lr of (result.lineResults ?? [])) {
    resultByLine.set(lr.lineNumber ?? 1, lr);
  }

  // Filter tokens: skip WS/NEWLINE, apply text filter
  const filtered: Token[] = [];
  for (let i = 0; i < rawTokens.length; i++) {
    const t = rawTokens[i];
    if (t.type === 'WS' || t.type === 'NEWLINE') continue;
    if (hasFilter && !matchToken(t, query)) continue;
    filtered.push(t);
  }

  const totalCount = filtered.length;

  if (groupByLine) {
    // Build line groups
    const lineMap = new Map<number, Token[]>();
    const lineOrder: number[] = [];
    for (let i = 0; i < filtered.length; i++) {
      const t = filtered[i];
      const ln = t.line ?? 1;
      if (!lineMap.has(ln)) { lineMap.set(ln, []); lineOrder.push(ln); }
      lineMap.get(ln)!.push(t);
    }
    lineOrder.sort((a, b) => a - b);

    const entries: GroupEntry[] = [];
    for (const ln of lineOrder) {
      entries.push({
        line: ln,
        tokens: lineMap.get(ln)!,
        result: resultByLine.get(ln) ?? null,
      });
    }
    groupEntries.value = entries;
    flatTokensList.value = [];

    let vis = 0;
    for (const e of entries) vis += e.tokens.length;
    visibleCount.value = vis;
  } else {
    groupEntries.value = [];
    flatTokensList.value = filtered;
    visibleCount.value = filtered.length;
  }

  // Build count label
  if (rawTokens.length === 0) {
    countLabel.value = '0 tokens';
  } else if (hasFilter) {
    countLabel.value = `${visibleCount.value} / ${totalCount} tokens`;
  } else {
    countLabel.value = `${totalCount} tokens`;
  }
}

// Watch for store changes
watch(
  () => [dr.result, tokens.filterQuery, tokens.groupByLine],
  () => updateDisplay(),
  { deep: false, immediate: true }
);

/* ── Tier summary ──────────────────────────────────────────── */
interface TierSummary {
  t1: number;
  t2: number;
  t3: number;
  skip: number;
  total: number;
}

const tierSummary = computed<TierSummary>(() => {
  const results = dr.lineResults;
  const s = { t1: 0, t2: 0, t3: 0, skip: 0, total: results.length };
  for (const r of results) {
    if (r.error) { s.skip++; continue; }
    if (r.wasCached) { s.t2++; continue; }
    if (r.type === 'Pending') { s.t3++; continue; }
    s.t1++;
  }
  return s;
});

/* ── Per-line tier breakdown for tooltips ──────────────────── */
const tierBreakdown = computed<{ t1: number[]; t2: number[]; t3: number[]; skip: { line: number; error: string; expr: string }[] }>(() => {
  const results = dr.lineResults;
  const b = { t1: [] as number[], t2: [] as number[], t3: [] as number[], skip: [] as { line: number; error: string; expr: string }[] };
  for (const r of results) {
    const ln = r.lineNumber ?? 1;
    if (r.error) { b.skip.push({ line: ln, error: r.error, expr: r.expression }); continue; }
    if (r.wasCached) { b.t2.push(ln); continue; }
    if (r.type === 'Pending') { b.t3.push(ln); continue; }
    b.t1.push(ln);
  }
  return b;
});

/** Pre-formatted tooltip strings for each tier pill — leads with what the
 * tier means, so hovering the pill is enough to learn it without a
 * separate legend to open. */
const tierTooltips = computed(() => {
  const b = tierBreakdown.value;
  const fmtLines = (nums: number[]) => nums.length > 0 ? '\nLines: ' + nums.join(', ') : '';
  const fmtSkip = b.skip.length > 0 ? '\n' + b.skip.map(s => 'L' + s.line + ' "' + s.expr + '": ' + s.error).join('\n') : '';
  return {
    t1: 'Fresh — full evaluation (lexer → parser → compiler → VM), nothing reused.' + fmtLines(b.t1),
    t2: 'Cached — bytecode reused from an earlier evaluation of the same expression.' + fmtLines(b.t2),
    t3: 'Pending — async data (e.g. a currency/price lookup) hasn\'t resolved yet.' + fmtLines(b.t3),
    skip: 'A parse or evaluation error.' + fmtSkip,
  };
});

/* ── Three-tier badge helpers ──────────────────────────────── */
function getTierClass(result: LineResult): string {
  if (result.error) return 'tier-skip';
  if (result.wasCached) return 'tier-2';
  if (result.type === 'Pending') return 'tier-3';
  return 'tier-1';
}

function getTierLabel(result: LineResult): string {
  if (result.error) return 'SKIP';
  if (result.wasCached) return 'T2';
  if (result.type === 'Pending') return 'T3';
  return 'T1';
}

/** Combined "tier + status" label for the single primary status chip. */
function getTierStatusLabel(result: LineResult): string {
  if (result.error) return 'Error';
  if (result.wasCached) return 'T2 Cached';
  if (result.type === 'Pending') return 'T3 Pending';
  return 'T1 Fresh';
}

function getTierReason(result: LineResult): string {
  if (result.error) return `Error: ${result.error}`;
  if (result.wasCached) return 'Tier 2 (Cache hit) — bytecode reused from earlier evaluation';
  if (result.type === 'Pending') return 'Tier 3 (Async pending) — awaiting external data resolution';
  return 'Tier 1 (Fresh) — full eval: lexer → parser → compiler → VM';
}

/* ── Copy all results ────────────────────────────────────────────── */
const hasAnyResults = computed(() => dr.lineResults.some(r => r.result || r.error));

function copyAllResults(): void {
  const text = dr.lineResults
    .map(r => `L${r.lineNumber ?? 1}: ${r.expression} = ${r.error ?? r.result ?? ''}`)
    .join('\n');
  if (!text) return;
  navigator.clipboard.writeText(text).catch(() => {
    const ta = document.createElement('textarea');
    ta.value = text;
    ta.style.position = 'fixed'; ta.style.left = '-9999px';
    document.body.appendChild(ta);
    ta.select();
    document.execCommand('copy');
    document.body.removeChild(ta);
  });
}

/* ── Copy result ──────────────────────────────────────────────── */
function copyResult(e: MouseEvent): void {
  const btn = (e.target as HTMLElement).closest('.token-line-result-copy') as HTMLElement | null;
  if (!btn) return;
  const text = btn.dataset.copy ?? '';
  if (!text) return;
  navigator.clipboard.writeText(text).then(() => {
    const orig = btn.innerHTML;
    btn.innerHTML = '<span class="msi msi-dense">check</span>';
    btn.classList.add('copied');
    setTimeout(() => { btn.innerHTML = orig; btn.classList.remove('copied'); }, 1000);
  }).catch(() => {
    const ta = document.createElement('textarea');
    ta.value = text;
    ta.style.position = 'fixed'; ta.style.left = '-9999px';
    document.body.appendChild(ta);
    ta.select();
    document.execCommand('copy');
    document.body.removeChild(ta);
  });
}
</script>
