// webapp/src/components/tabs/VmTraceTab.tsx
import { useMemo, useState } from "react"
import { Zap } from "lucide-react"
import { useDiagnosticReportStore, expression as selectExpression } from "@/stores/diagnosticReport"
import { usePipelineStore } from "@/stores/pipeline"
import { formatStackValue, stackValueTypeClass, fmt } from "@bridge/utils"
import { ContextHeader } from "@/components/shared/ContextHeader"
import { EmptyState } from "@/components/shared/EmptyState"
import { Input } from "@/components/ui/input"
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from "@/components/ui/table"
import { cn } from "@/lib/utils"

const STACK_TYPE_COLOR: Record<string, string> = {
  "vm-stack-number": "border-blue-500/40 text-blue-600 dark:text-blue-400",
  "vm-stack-hex": "border-indigo-500/40 text-indigo-600 dark:text-indigo-400",
  "vm-stack-bigint": "border-violet-500/40 text-violet-600 dark:text-violet-400",
  "vm-stack-string": "border-emerald-500/40 text-emerald-600 dark:text-emerald-400",
  "vm-stack-datetime": "border-amber-500/40 text-amber-600 dark:text-amber-400",
  "vm-stack-percentage": "border-pink-500/40 text-pink-600 dark:text-pink-400",
  "vm-stack-uom": "border-cyan-500/40 text-cyan-600 dark:text-cyan-400",
  "vm-stack-array": "border-orange-500/40 text-orange-600 dark:text-orange-400",
  "vm-stack-boolean": "border-teal-500/40 text-teal-600 dark:text-teal-400",
  "vm-stack-other": "border-muted-foreground/30 text-muted-foreground",
}

/** Ported from playground's VmTraceTab.vue. */
export function VmTraceTab() {
  const steps = useDiagnosticReportStore((s) => s.vmTrace)
  const checkpoints = useDiagnosticReportStore((s) => s.checkpoints)
  const lineResults = useDiagnosticReportStore((s) => s.lineResults)
  const expression = useDiagnosticReportStore(selectExpression)
  const selectedLine = usePipelineStore((s) => s.selectedLine)
  const [filterQuery, setFilterQuery] = useState("")

  const filteredSteps = useMemo(() => {
    const q = filterQuery.trim().toLowerCase()
    if (!q) return steps
    return steps.filter((s) => s.opcodeName.toLowerCase().includes(q))
  }, [steps, filterQuery])

  // The checkpoint at the highest line number recorded — NOT actually
  // "nearest to the current execution point" despite what the original
  // label implied (no correlation against ip/instructionNumber is computed).
  const latestCheckpoint = useMemo(() => {
    if (checkpoints.length === 0) return null
    return checkpoints.reduce((a, b) => (a.lineNumber > b.lineNumber ? a : b))
  }, [checkpoints])

  const lineBadge = selectedLine !== null ? `L${selectedLine}` : "All Lines"
  const activeExpression =
    selectedLine !== null
      ? (lineResults.find((r) => r.lineNumber === selectedLine)?.expression ?? "")
      : (lineResults[0]?.expression ?? expression ?? "")

  return (
    <div className="flex min-h-0 flex-1 flex-col">
      <ContextHeader
        label="VM Trace"
        lineBadge={lineBadge}
        expression={activeExpression}
        extra={
          <Input
            value={filterQuery}
            onChange={(e) => setFilterQuery(e.target.value)}
            placeholder="Filter opcodes…"
            spellCheck={false}
            className="h-7 max-w-35 text-xs"
          />
        }
      />
      <div className="border-b px-4 py-1.5">
        <span className="text-muted-foreground text-xs">
          {filteredSteps.length} / {steps.length} steps
        </span>
      </div>

      {checkpoints.length > 0 && (
        <div className="bg-muted/30 flex flex-col gap-1.5 border-b px-4 py-2">
          <div className="flex items-center gap-3">
            <span className="text-xs font-medium">Checkpoints ({checkpoints.length})</span>
            <span
              title="The checkpoint at the highest line number recorded so far — not necessarily the one closest to the last-executed instruction pointer."
              className="text-muted-foreground text-xs"
            >
              ▼ Latest: L{latestCheckpoint?.lineNumber ?? "—"}{" "}
              <span className="text-muted-foreground/70">({latestCheckpoint?.variableCount ?? 0} vars)</span>
            </span>
          </div>
          <div className="flex flex-wrap gap-1.5">
            {checkpoints.map((cp) => (
              <span
                key={cp.lineNumber}
                title={`${cp.variables.length} variable(s): ${cp.variables.join(", ")}`}
                className={cn(
                  "flex items-center gap-1 rounded-md border px-2 py-0.5 font-mono text-xs",
                  cp.lineNumber === latestCheckpoint?.lineNumber && "border-primary bg-primary/10",
                )}
              >
                L{cp.lineNumber} <span className="text-muted-foreground">({cp.variableCount} vars)</span>
                {cp.lineNumber === latestCheckpoint?.lineNumber && <span className="text-primary">◀ latest</span>}
              </span>
            ))}
          </div>
          <div className="text-muted-foreground/70 text-xs">
            Checkpoints record VM variable state at definition lines for fast restoration.
          </div>
        </div>
      )}

      <div className="flex min-h-0 flex-1 flex-col overflow-hidden">
        {steps.length === 0 ? (
          <EmptyState icon={Zap} text="No trace data" hint="Evaluate an expression to see its step-by-step VM execution trace." />
        ) : filteredSteps.length === 0 ? (
          <div className="text-muted-foreground p-2.5 text-sm">No steps match &ldquo;{filterQuery}&rdquo;</div>
        ) : (
          <div className="flex-1 overflow-y-auto">
            <Table className="font-mono text-xs">
              <TableHeader className="bg-background sticky top-0">
                <TableRow>
                  <TableHead className="w-12">#</TableHead>
                  <TableHead className="w-12">IP</TableHead>
                  <TableHead className="w-16">Hex</TableHead>
                  <TableHead className="w-32">Opcode</TableHead>
                  <TableHead>Stack</TableHead>
                  <TableHead className="w-20">Elapsed</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {filteredSteps.map((step, i) => (
                  <TableRow key={i} className={cn(step === steps[steps.length - 1] && "bg-destructive/5")}>
                    <TableCell>{step.instructionNumber}</TableCell>
                    <TableCell>{step.ip}</TableCell>
                    <TableCell className="text-blue-600 dark:text-blue-400">0x{step.opcode.toString(16).toUpperCase().padStart(2, "0")}</TableCell>
                    <TableCell className="font-semibold text-violet-600 dark:text-violet-400">{step.opcodeName}</TableCell>
                    <TableCell className="whitespace-normal">
                      <span className="flex flex-wrap items-center gap-1">
                        <span className="bg-muted rounded px-1 text-[10px]">{step.stackDepth}</span>
                        {(step.stack ?? []).length === 0 ? (
                          <span className="text-muted-foreground/50">∅</span>
                        ) : (
                          (step.stack ?? []).map((sv, si) => (
                            <span
                              key={si}
                              title={`Type ${sv.type}${sv.unit ? ` Unit: ${sv.unit}` : ""}`}
                              className={cn("rounded border px-1 py-0.5 text-[10px]", STACK_TYPE_COLOR[stackValueTypeClass(sv.type)])}
                            >
                              {formatStackValue(sv)}
                            </span>
                          ))
                        )}
                      </span>
                    </TableCell>
                    <TableCell className="text-muted-foreground">{fmt(step.elapsedNs)}</TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>
        )}
      </div>
    </div>
  )
}

// playground/src/components/VmTraceTab.vue
<template>
  <div class="tab-panel active" id="panel-vmtrace">
    <context-header label="VM Trace" :line-badge="lineBadge" :expression="activeExpression">
      <template #extra>
        <input type="text" class="token-filter-input" placeholder="Filter opcodes…" spellcheck="false" v-model="filterQuery" style="max-width: 140px;" />
      </template>
    </context-header>
    <div class="panel-toolbar">
      <span class="bytecode-count">{{ filteredSteps.length }} / {{ steps.length }} steps</span>
    </div>

    <!-- Checkpoint markers -->
    <div v-if="checkpoints.length > 0" class="vm-checkpoints-bar">
      <div class="vm-checkpoints-bar-top">
        <span class="vm-checkpoints-title">Checkpoints ({{ checkpoints.length }})</span>
        <span class="vm-checkpoint-nearest" title="The checkpoint at the highest line number recorded so far — not necessarily the one closest to the last-executed instruction pointer.">
          ▼ Latest: L{{ latestCheckpoint?.lineNumber ?? '—' }}
          <span class="vm-checkpoint-nearest-vars">({{ latestCheckpoint?.variableCount ?? 0 }} vars)</span>
        </span>
      </div>
      <div class="vm-checkpoints-chips">
        <span
          v-for="cp in checkpoints"
          :key="cp.lineNumber"
          class="vm-checkpoint-chip"
          :class="{ 'vm-checkpoint-active': cp.lineNumber === latestCheckpoint?.lineNumber }"
          :title="cp.variables.length + ' variable(s): ' + cp.variables.join(', ')"
        >
          L{{ cp.lineNumber }}
          <span class="vm-checkpoint-var-count">({{ cp.variableCount }} vars)</span>
          <span v-if="cp.lineNumber === latestCheckpoint?.lineNumber" class="vm-checkpoint-arrow">◀ latest</span>
        </span>
      </div>
      <div class="vm-checkpoints-note">
        Checkpoints record VM variable state at definition lines for fast restoration.
      </div>
    </div>

    <div class="vm-trace-table">
      <div class="vm-trace-header-row">
        <span class="vm-trace-col-step">#</span>
        <span class="vm-trace-col-ip">IP</span>
        <span class="vm-trace-col-hex">Hex</span>
        <span class="vm-trace-col-op">Opcode</span>
        <span class="vm-trace-col-stack">Stack</span>
        <span class="vm-trace-col-time">Elapsed</span>
      </div>
      <div class="panel-scroll">
        <empty-state v-if="steps.length === 0" icon="bolt" text="No trace data" hint="Evaluate an expression to see its step-by-step VM execution trace." />
        <div v-else-if="filteredSteps.length === 0" class="empty" style="padding: 10px;">No steps match &ldquo;{{ filterQuery }}&rdquo;</div>
        <div v-for="(step, i) in filteredSteps" :key="i" class="vm-trace-row" :class="{ halt: step === steps[steps.length - 1] }">
          <span class="vm-trace-col-step">{{ step.instructionNumber }}</span>
          <span class="vm-trace-col-ip">{{ step.ip }}</span>
          <span class="vm-trace-col-hex">0x{{ step.opcode.toString(16).toUpperCase().padStart(2, '0') }}</span>
          <span class="vm-trace-col-op">{{ step.opcodeName }}</span>
          <span class="vm-trace-col-stack">
            <span class="vm-trace-stack-depth-badge">{{ step.stackDepth }}</span>
            <span class="vm-trace-stack-chips">
              <span v-if="(step.stack ?? []).length === 0" class="vm-stack-empty">∅</span>
              <span
                v-for="(sv, si) in step.stack ?? []"
                :key="si"
                class="vm-stack-chip"
                :class="stackValueTypeClass(sv.type)"
                :title="'Type ' + sv.type + (sv.unit ? ' Unit: ' + sv.unit : '')"
              >{{ formatStackValue(sv) }}</span>
            </span>
          </span>
          <span class="vm-trace-col-time">{{ fmt(step.elapsedNs) }}</span>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, ref } from 'vue';
import { useDiagnosticReportStore } from '../stores/diagnosticReport.js';
import { usePipelineStore } from '../stores/pipeline.js';
import { formatStackValue, stackValueTypeClass, fmt } from '@bridge/utils';
import type { VmTraceStep, CheckpointSnapshot } from '@bridge/engine';
import ContextHeader from './shared/ContextHeader.vue';
import EmptyState from './shared/EmptyState.vue';

const dr = useDiagnosticReportStore();
const pl = usePipelineStore();
const steps = computed<VmTraceStep[]>(() => dr.vmTrace);
const checkpoints = computed<CheckpointSnapshot[]>(() => dr.checkpoints);

const filterQuery = ref('');
const filteredSteps = computed(() => {
  const q = filterQuery.value.trim().toLowerCase();
  if (!q) return steps.value;
  return steps.value.filter(s => s.opcodeName.toLowerCase().includes(q));
});

/**
 * The checkpoint at the highest line number recorded — NOT actually
 * "nearest to the current execution point" despite the label this used
 * to have (there's no correlation computed against `ip`/`instructionNumber`
 * here). Renamed to "Latest" to describe what this actually computes.
 */
const latestCheckpoint = computed<CheckpointSnapshot | null>(() => {
  const cps = checkpoints.value;
  if (cps.length === 0) return null;
  return cps.reduce((a, b) => (a.lineNumber > b.lineNumber ? a : b));
});

/* ── Context header ────────────────────────────────────────────── */
const lineBadge = computed(() => (pl.selectedLine !== null ? 'L' + pl.selectedLine : 'All Lines'));
const activeExpression = computed(() => {
  const ln = pl.selectedLine;
  if (ln !== null) {
    const lr = dr.lineResults.find(r => r.lineNumber === ln);
    return lr?.expression ?? '';
  }
  const first = dr.lineResults[0];
  return first?.expression ?? dr.expression ?? '';
});
</script>
