// playground/src/components/EditorPane.vue
<template>
  <main class="editor-pane" id="editor-pane" :class="{ collapsed: ui.editorCollapsed }">
    <div class="editor-pane-header">
      <span class="pane-title">Editor</span>
      <ExamplesMenu />
    </div>
    <div class="editor-wrapper" ref="editorRef"></div>
  </main>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted, watch } from 'vue';
import { EditorView, keymap, placeholder, Decoration, WidgetType, ViewPlugin, type ViewUpdate, type DecorationSet } from '@codemirror/view';
import { EditorState, StateField, RangeSetBuilder, RangeSet, StateEffect } from '@codemirror/state';
import { autocompletion, type CompletionContext, type CompletionResult } from '@codemirror/autocomplete';
import { basicSetup } from 'codemirror';
import { markdown } from '@codemirror/lang-markdown';
import { oneDark } from '@codemirror/theme-one-dark';
import { ExpressionEngine } from '@solve-js/engine/ExpressionEngine';
import { SolveLanguageService } from '@solve-js/language/SolveLanguageService';
import { categoryClassName, completionItemToOption } from '@solve-js/language/adapters/codemirror';
import { useEngineStore } from '../stores/engine.js';
import { useDiagnosticReportStore } from '../stores/diagnosticReport.js';
import { useEditorStore } from '../stores/editor.js';
import { usePipelineStore } from '../stores/pipeline.js';
import { useUiStore } from '../stores/ui.js';
import type { LineResult } from '../engine.js';
import { prepareEvaluationInput } from '../engineShared.js';
import ExamplesMenu from './ExamplesMenu.vue';

const engine = useEngineStore();
const dr = useDiagnosticReportStore();
const editorStore = useEditorStore();
const pipeline = usePipelineStore();
const ui = useUiStore();

// Dedicated main-thread engine purely for lexing/highlighting — the actual
// evaluation path (useEngineStore) runs through a Web Worker, the wrong
// tool for a synchronous per-keystroke operation. BUILTIN_PACKAGES-only
// today (the playground doesn't register OSRS or any other opt-in package
// anywhere — confirmed via grep); keep this in sync if that ever changes,
// since a mismatch would mean plugin-contributed tokens silently render
// unstyled here even though they're correctly recognized during evaluation.
const highlightEngine = new ExpressionEngine('en', false);
// highlightEngine never evaluates anything, so its own DAG is always empty —
// without this override, a lone bare word (e.g. "hello") would never be
// recognized as a real variable reference here even when it genuinely is
// one elsewhere in the document (":hello = 1"), since SolveLanguageService's
// default variable-name source reads from the SAME engine it lexes with.
// Read from the real evaluation engine's already-computed DAG snapshot
// instead (dr.dagSnapshot, populated from the worker-backed engine's own
// DependencyGraph — see DagTab.vue for the same access pattern).
const languageService = new SolveLanguageService(highlightEngine, {
  variableNameSource: () => {
    const snap = dr.dagSnapshot;
    if (!snap) return [];
    return [...Object.keys(snap.consumers), ...Object.values(snap.writes).flat()];
  },
});

/**
 * CM6 CompletionSource for the playground's editor, delegating to the same
 * languageService.getCompletions() the real Obsidian editor uses (see
 * MarkdownEditorViewPlugin.completionSource for the equivalent there). No
 * enabled/disabled setting here — the playground is a diagnostic tool with
 * no settings UI, matching the same precedent as syntax highlighting.
 */
function solveCompletionSource(context: CompletionContext): CompletionResult | null {
  const word = context.matchBefore(/[\w]+/);
  if (!word || (word.from === word.to && !context.explicit)) return null;

  const line = context.state.doc.lineAt(context.pos);
  const items = languageService.getCompletions(line.text, context.pos - line.from);
  if (items.length === 0) return null;

  return { from: word.from, options: items.map(completionItemToOption) };
}

/* ── Inline Result Widget ─────────────────────────────────────── */
class ResultWidget extends WidgetType {
  constructor(readonly text: string, readonly type: string, readonly pending = false) { super(); }
  eq(other: ResultWidget) {
    return this.text === other.text && this.type === other.type && this.pending === other.pending;
  }
  toDOM() {
    const span = document.createElement('span');
    span.title = this.pending ? 'Awaiting async resolution…' : this.type;

    if (this.pending) {
      // Matches the real Obsidian widget's spinner treatment
      // (ExpressionResultWidget.ts) — a rotating icon plus a label,
      // rather than a plain pulsing "…" text.
      span.className = 'os-result-inline os-result-pending';
      const spinner = document.createElement('span');
      spinner.className = 'os-result-inline-spinner';
      spinner.textContent = '⟳';
      const label = document.createElement('span');
      label.className = 'os-result-inline-pending-label';
      label.textContent = '...';
      span.appendChild(spinner);
      span.appendChild(label);
      return span;
    }

    span.className = 'os-result-inline';
    span.textContent = this.text;
    return span;
  }
}

const resultEffect = StateEffect.define<{ from: number; to: number; deco: Decoration }[]>();
const resultField = StateField.define<RangeSet<Decoration>>({
  create() { return Decoration.none; },
  update(set, tr) {
    for (const e of tr.effects) {
      if (e.is(resultEffect)) {
        const builder = new RangeSetBuilder<Decoration>();
        for (const { from, to, deco } of e.value) builder.add(from, to, deco);
        return builder.finish();
      }
    }
    return set.map(tr.changes);
  },
  provide: f => EditorView.decorations.from(f),
});

/**
 * Syntax highlighting for solve expressions, driven by the engine-agnostic
 * SolveLanguageService + CodeMirror adapter. Wraps every semantically
 * classified token (numbers, operators, keywords, variables, punctuation,
 * ...) with a `cm-solve-{category}` decoration.
 *
 * A ViewPlugin rather than a StateField specifically so it can read
 * `view.visibleRanges` — only the lines actually on screen are lexed on
 * every rebuild, matching the real Obsidian editor's viewport-only
 * approach. An earlier version iterated the WHOLE document on every
 * rebuild regardless of scroll position, which meant every keystroke in a
 * large document re-lexed lines nobody could even see.
 *
 * Invalidation is surgical: only the lines actually touched by a change
 * are evicted from the language service's cache (via `invalidateLines`),
 * so editing one line doesn't force every other visible line's decorations
 * to be recomputed from scratch on the next render.
 */
class SolveHighlightPluginValue {
  decorations: DecorationSet;

  constructor(view: EditorView) {
    this.decorations = this.buildDecorations(view);
  }

  update(update: ViewUpdate): void {
    if (update.docChanged) {
      const changedLines = new Set<number>();
      update.changes.iterChangedRanges((_fromA, _toA, fromB, toB) => {
        const startLine = update.state.doc.lineAt(fromB).number;
        const endLine = update.state.doc.lineAt(toB).number;
        for (let line = startLine; line <= endLine; line++) changedLines.add(line);
      });
      languageService.invalidateLines(changedLines);
      this.decorations = this.buildDecorations(update.view);
    } else if (update.viewportChanged) {
      this.decorations = this.buildDecorations(update.view);
    }
  }

  private buildDecorations(view: EditorView): DecorationSet {
    const builder = new RangeSetBuilder<Decoration>();
    for (const { from, to } of view.visibleRanges) {
      let pos = from;
      while (pos <= to) {
        const line = view.state.doc.lineAt(pos);
        for (const token of languageService.getSemanticTokens(line.text, line.number)) {
          builder.add(
            line.from + token.from,
            line.from + token.to,
            Decoration.mark({ class: categoryClassName(token.category) }),
          );
        }
        pos = line.to + 1;
      }
    }
    return builder.finish();
  }
}

const solveHighlightPlugin = ViewPlugin.fromClass(SolveHighlightPluginValue, {
  decorations: v => v.decorations,
});

// Built once — a fresh RegExp literal was allocated on every create()/update()
// call. `g`-flagged regexes are stateful (lastIndex), which is exactly why
// every loop below resets `.lastIndex = 0` before reusing it; sharing one
// instance across calls is safe as long as that reset happens first.
const INLINE_SOLVE_RE = /s`[^`]*`/g;

/**
 * Highlights inline solve regions (`s`...``) within the editor.
 *
 * Inline solves are expressions embedded in markdown lines using the syntax
 * `s`2 + 3``. These regions get a distinct background decoration so users
 * can visually identify where inline solves are active.
 *
 * The pattern matches `s` followed by any non-backtick content, then a
 * closing backtick. Highlights are applied as a background tint with rounded
 * corners, similar to a code-fence inline visual.
 *
 * A ViewPlugin rather than a StateField, mirroring SolveHighlightPluginValue
 * above — for the same reason: only `view.visibleRanges` is scanned on every
 * rebuild, not the whole document. An earlier version was a StateField that
 * re-scanned every line in the document on every single keystroke regardless
 * of scroll position, the same whole-document antipattern that class's own
 * doc comment already describes fixing for syntax highlighting.
 */
class InlineSolvePluginValue {
  decorations: DecorationSet;

  constructor(view: EditorView) {
    this.decorations = this.buildDecorations(view);
  }

  update(update: ViewUpdate): void {
    if (update.docChanged || update.viewportChanged) {
      this.decorations = this.buildDecorations(update.view);
    }
  }

  private buildDecorations(view: EditorView): DecorationSet {
    const builder = new RangeSetBuilder<Decoration>();
    for (const { from, to } of view.visibleRanges) {
      let pos = from;
      while (pos <= to) {
        const line = view.state.doc.lineAt(pos);
        INLINE_SOLVE_RE.lastIndex = 0;
        let m: RegExpExecArray | null;
        while ((m = INLINE_SOLVE_RE.exec(line.text)) !== null) {
          builder.add(
            line.from + m.index,
            line.from + m.index + m[0].length,
            Decoration.mark({ class: 'cm-inline-solve' }),
          );
        }
        pos = line.to + 1;
      }
    }
    return builder.finish();
  }
}

const inlineSolveField = ViewPlugin.fromClass(InlineSolvePluginValue, {
  decorations: v => v.decorations,
});

/* ── Editor Setup ─────────────────────────────────────────────── */
const editorRef = ref<HTMLElement | null>(null);
let editorView: EditorView | null = null;

const EDITOR_THEME = EditorView.theme({
  '&': { height: '100%' },
  '.cm-scroller': { overflow: 'auto' },
});

onMounted(() => {
  if (!editorRef.value) return;

  const initialDoc = '10 + 5 * 2\nosrs(Iron Axe)';

  editorView = new EditorView({
    state: EditorState.create({
      doc: initialDoc,
      extensions: [
        basicSetup, markdown(), oneDark, solveHighlightPlugin, inlineSolveField, resultField,
        autocompletion({ override: [solveCompletionSource] }),
        placeholder('Enter an expression…  e.g. 10 + 5 * 2'),
        EditorView.updateListener.of((update) => {
          if (update.docChanged) {
            // See prepareEvaluationInput()'s doc comment — the document
            // text must reach the engine unmodified (never .trim()'d) so
            // every line's reported lineNumber stays aligned with its
            // actual position in the document.
            const expr = prepareEvaluationInput(update.state.doc.toString());
            // Highlight cache invalidation is now handled surgically, per
            // changed line, inside SolveHighlightPluginValue.update() —
            // no blanket clear needed here.
            engine.evaluate(expr);
          }
          if (update.selectionSet) {
            const pos = update.state.selection.main.head;
            const line = update.state.doc.lineAt(pos);
            editorStore.updateCursorLine(line.number);
          }
        }),
        keymap.of([{ key: 'Ctrl-Enter', run: () => { run(); return true; } }]),
        EDITOR_THEME,
      ],
    }),
    parent: editorRef.value,
  });

  // Trigger initial evaluation
  engine.evaluate(initialDoc);
});

onUnmounted(() => {
  editorView?.destroy();
  editorView = null;
});

/* ── Public methods ───────────────────────────────────────────── */
function run(): void {
  if (!editorView) return;
  engine.evaluate(prepareEvaluationInput(editorView.state.doc.toString()));
}

function insertExample(expression: string): void {
  if (!editorView) return;
  editorView.dispatch({ changes: { from: 0, to: editorView.state.doc.length, insert: expression } });
}

function renderInlineResults(lineResults: LineResult[]): void {
  if (!editorView) return;
  // Guard against destroyed editor (HMR unmount leaves stale reference)
  if (!editorView.dom || !editorView.dom.parentNode) return;
  const effects: { from: number; to: number; deco: Decoration }[] = [];
  for (const lr of lineResults) {
    if (lr.error) continue;
    const isPending = lr.type === 'Pending';
    // A Pending result formats to "" (see formatLineResultValue in
    // engineShared.ts — the queryKey must never be shown as if it were
    // the answer), so it needs its own branch instead of the `!lr.result`
    // skip other empty/non-evaluable lines take.
    if (!lr.result && !isPending) continue;
    const line = editorView.state.doc.line(lr.lineNumber ?? 1);
    const text = isPending ? '…' : lr.result;
    effects.push({ from: line.to, to: line.to, deco: Decoration.widget({ widget: new ResultWidget(text, lr.type, isPending), side: 1 }) });
  }
  // Always dispatch, even with an empty effects array: resultField's update()
  // rebuilds the ENTIRE decoration set from this list every time, so skipping
  // the dispatch when every line errored (or otherwise produced no widget)
  // left whatever was previously rendered — e.g. a stale "= 293.00 gp" from
  // the last successful evaluation — stuck on screen after the line was
  // edited into something that no longer parses.
  editorView.dispatch({ effects: resultEffect.of(effects) });
}

// Expose for parent to call
defineExpose({ insertExample, renderInlineResults });

// Update cursor line in pipeline when store changes
watch(() => editorStore.cursorLine, (line) => {
  pipeline.selectLine(line, false);
});

// Watch for results to render inline decorators
watch(() => dr.result, (result) => {
  if (result) {
    requestAnimationFrame(() => renderInlineResults(result.lineResults));
  }
});
</script>

<style scoped>
:deep(.cm-inline-solve) {
  background: rgba(199, 169, 255, 0.12);
  border-radius: 3px;
  border: 1px solid rgba(199, 169, 255, 0.25);
  box-shadow: inset 0 0 0 1px rgba(199, 169, 255, 0.08);
  transition: background 0.2s;
}
:deep(.cm-inline-solve:hover) {
  background: rgba(199, 169, 255, 0.2);
}

/* Syntax highlight colors — "One Dark" palette. The playground is a
   diagnostic tool with no settings UI, so these are hardcoded rather than
   driven by CSS custom properties (unlike the real Obsidian plugin, where
   the same class names resolve `--solve-hl-*` variables from user
   settings — see src/app/styles.css). */
:deep(.cm-solve-number) { color: #61AFEF; }
:deep(.cm-solve-string) { color: #98C379; }
:deep(.cm-solve-keyword) { color: #C678DD; }
:deep(.cm-solve-operator) { color: #ABB2BF; }
:deep(.cm-solve-comparison) { color: #56B6C2; }
:deep(.cm-solve-bitwise) { color: #56B6C2; }
:deep(.cm-solve-function) { color: #E5C07B; }
:deep(.cm-solve-variable) { color: #E06C75; }
:deep(.cm-solve-unit) { color: #56B6C2; }
:deep(.cm-solve-datetime) { color: #D19A66; }
:deep(.cm-solve-vector) { color: #D19A66; }
:deep(.cm-solve-punctuation) { color: #5C6370; }
:deep(.cm-solve-error) { color: #E06C75; text-decoration: underline wavy; }
:deep(.cm-solve-osrs-item) { color: #A6E22E; font-weight: 600; }
</style>

// webapp/src/components/EditorPane.tsx
import { useEffect, useRef } from "react"
import { Code2 } from "lucide-react"
import {
  EditorView,
  keymap,
  placeholder,
  Decoration,
  WidgetType,
  ViewPlugin,
  type ViewUpdate,
  type DecorationSet,
} from "@codemirror/view"
import { EditorState, StateField, RangeSetBuilder, RangeSet, StateEffect } from "@codemirror/state"
import { autocompletion, type CompletionContext, type CompletionResult } from "@codemirror/autocomplete"
import { basicSetup } from "codemirror"
import { markdown } from "@codemirror/lang-markdown"
import { oneDark } from "@codemirror/theme-one-dark"
import { ExpressionEngine } from "@solve-js/engine/ExpressionEngine"
import { LanguageService } from "@solve-js/language/LanguageService"
import { categoryClassName, completionItemToOption } from "@solve-js/language/adapters/codemirror"
import { BUILTIN_PACKAGES } from "@solve-js/packages/builtins"
import { OSRS_PACKAGE } from "@solve-js-examples/osrs/OsrsPackage"
import type { LineResult } from "@bridge/engine"
import { prepareEvaluationInput } from "@bridge/engineShared"
import * as engineService from "@/stores/engine"
import { useDiagnosticReportStore } from "@/stores/diagnosticReport"
import { useEditorStore } from "@/stores/editor"
import { usePipelineStore } from "@/stores/pipeline"
import { useTabsStore } from "@/stores/tabsStore"
import { useUiStore } from "@/stores/ui"
import { TabBar } from "@/components/TabBar"
import { ExamplesMenu } from "@/components/ExamplesMenu"
import { cn } from "@/lib/utils"

/* ── Inline Result Widget ─────────────────────────────────────────────── */
class ResultWidget extends WidgetType {
  constructor(
    readonly text: string,
    readonly type: string,
    readonly pending = false,
  ) {
    super()
  }
  eq(other: ResultWidget) {
    return this.text === other.text && this.type === other.type && this.pending === other.pending
  }
  toDOM() {
    const span = document.createElement("span")
    span.title = this.pending ? "Awaiting async resolution…" : this.type

    if (this.pending) {
      span.className = "os-result-inline os-result-pending"
      const spinner = document.createElement("span")
      spinner.className = "os-result-inline-spinner"
      spinner.textContent = "⟳"
      const label = document.createElement("span")
      label.className = "os-result-inline-pending-label"
      label.textContent = "..."
      span.appendChild(spinner)
      span.appendChild(label)
      return span
    }

    span.className = "os-result-inline"
    span.textContent = this.text
    return span
  }
}

const resultEffect = StateEffect.define<{ from: number; to: number; deco: Decoration }[]>()
const resultField = StateField.define<RangeSet<Decoration>>({
  create() {
    return Decoration.none
  },
  update(set, tr) {
    for (const e of tr.effects) {
      if (e.is(resultEffect)) {
        const builder = new RangeSetBuilder<Decoration>()
        for (const { from, to, deco } of e.value) builder.add(from, to, deco)
        return builder.finish()
      }
    }
    return set.map(tr.changes)
  },
  provide: (f) => EditorView.decorations.from(f),
})

// `g`-flagged regexes are stateful (lastIndex) — every loop resets it before
// reuse, so sharing one instance across every tab's editor is safe.
const INLINE_SOLVE_RE = /s`[^`]*`/g

/**
 * Highlights inline solve regions (`` s`...` ``) within the editor. A
 * ViewPlugin so it can read `view.visibleRanges` — only lines actually on
 * screen are scanned on every rebuild.
 */
class InlineSolvePluginValue {
  decorations: DecorationSet

  constructor(view: EditorView) {
    this.decorations = this.buildDecorations(view)
  }

  update(update: ViewUpdate): void {
    if (update.docChanged || update.viewportChanged) {
      this.decorations = this.buildDecorations(update.view)
    }
  }

  private buildDecorations(view: EditorView): DecorationSet {
    const builder = new RangeSetBuilder<Decoration>()
    for (const { from, to } of view.visibleRanges) {
      let pos = from
      while (pos <= to) {
        const line = view.state.doc.lineAt(pos)
        INLINE_SOLVE_RE.lastIndex = 0
        let m: RegExpExecArray | null
        while ((m = INLINE_SOLVE_RE.exec(line.text)) !== null) {
          builder.add(line.from + m.index, line.from + m.index + m[0].length, Decoration.mark({ class: "cm-inline-solve" }))
        }
        pos = line.to + 1
      }
    }
    return builder.finish()
  }
}

const inlineSolveField = ViewPlugin.fromClass(InlineSolvePluginValue, {
  decorations: (v) => v.decorations,
})

/**
 * Per-tab state that CANNOT be shared across tabs — each open document gets
 * its own main-thread highlighting engine and language service, mirroring
 * how the real Obsidian plugin gives each editor pane its own
 * ExpressionEngine.
 */
interface TabEditor {
  view: EditorView
  highlightEngine: ExpressionEngine
  languageService: LanguageService
}

const EDITOR_THEME = EditorView.theme({
  "&": { height: "100%" },
  ".cm-scroller": { overflow: "auto" },
})

/** Builds the syntax-highlighting ViewPlugin for ONE tab, closing over that tab's own languageService instance. */
function createHighlightPlugin(languageService: LanguageService) {
  class SolveHighlightPluginValue {
    decorations: DecorationSet

    constructor(view: EditorView) {
      this.decorations = this.buildDecorations(view)
    }

    update(update: ViewUpdate): void {
      if (update.docChanged) {
        const changedLines = new Set<number>()
        update.changes.iterChangedRanges((_fromA, _toA, fromB, toB) => {
          const startLine = update.state.doc.lineAt(fromB).number
          const endLine = update.state.doc.lineAt(toB).number
          for (let line = startLine; line <= endLine; line++) changedLines.add(line)
        })
        languageService.invalidateLines(changedLines)
        this.decorations = this.buildDecorations(update.view)
      } else if (update.viewportChanged) {
        this.decorations = this.buildDecorations(update.view)
      }
    }

    private buildDecorations(view: EditorView): DecorationSet {
      const builder = new RangeSetBuilder<Decoration>()
      for (const { from, to } of view.visibleRanges) {
        let pos = from
        while (pos <= to) {
          const line = view.state.doc.lineAt(pos)
          for (const token of languageService.getSemanticTokens(line.text, line.number)) {
            builder.add(line.from + token.from, line.from + token.to, Decoration.mark({ class: categoryClassName(token.category) }))
          }
          pos = line.to + 1
        }
      }
      return builder.finish()
    }
  }

  return ViewPlugin.fromClass(SolveHighlightPluginValue, {
    decorations: (v) => v.decorations,
  })
}

/** Creates the CodeMirror EditorView for one tab, including its own highlighting engine/language service. */
function createTabEditor(tabId: string, container: HTMLElement, initialDoc: string): TabEditor {
  // OSRS is an example package, not a built-in — registered explicitly
  // alongside BUILTIN_PACKAGES so "osrs"/game-item tokens still highlight
  // correctly. Keep this in sync with engine.ts's PLAYGROUND_PACKAGES.
  const highlightEngine = new ExpressionEngine("en", false, undefined, undefined, [...BUILTIN_PACKAGES, OSRS_PACKAGE])
  // highlightEngine never evaluates anything, so its own DAG is always
  // empty — read variable names from the real evaluation engine's
  // already-computed DAG snapshot instead (the ACTIVE tab's snapshot).
  const languageService = new LanguageService(highlightEngine, {
    variableNameSource: () => {
      const snap = useDiagnosticReportStore.getState().dagSnapshot
      if (!snap) return []
      return [...Object.keys(snap.consumers), ...Object.values(snap.writes).flat()]
    },
  })

  function solveCompletionSource(context: CompletionContext): CompletionResult | null {
    const word = context.matchBefore(/[\w]+/)
    if (!word || (word.from === word.to && !context.explicit)) return null

    const line = context.state.doc.lineAt(context.pos)
    const items = languageService.getCompletions(line.text, context.pos - line.from)
    if (items.length === 0) return null

    return { from: word.from, options: items.map(completionItemToOption) }
  }

  const view = new EditorView({
    state: EditorState.create({
      doc: initialDoc,
      extensions: [
        basicSetup,
        markdown(),
        oneDark,
        createHighlightPlugin(languageService),
        inlineSolveField,
        resultField,
        autocompletion({ override: [solveCompletionSource] }),
        placeholder("Enter an expression…  e.g. 10 + 5 * 2"),
        EditorView.updateListener.of((update) => {
          if (update.docChanged) {
            // The document text must reach the engine unmodified (never
            // .trim()'d) so every line's reported lineNumber stays aligned
            // with its actual position in the document.
            const expr = prepareEvaluationInput(update.state.doc.toString())
            useTabsStore.getState().updateTabText(tabId, expr)
            engineService.evaluate(expr, tabId)
          }
          if (update.selectionSet && tabId === useTabsStore.getState().activeTabId) {
            const pos = update.state.selection.main.head
            const line = update.state.doc.lineAt(pos)
            useEditorStore.getState().updateCursorLine(line.number)
          }
        }),
        keymap.of([
          {
            key: "Ctrl-Enter",
            run: () => {
              run(tabId)
              return true
            },
          },
        ]),
        EDITOR_THEME,
      ],
    }),
    parent: container,
  })

  return { view, highlightEngine, languageService }
}

function run(tabId?: string): void {
  const id = tabId ?? useTabsStore.getState().activeTabId
  const editor = tabEditorsSingleton.get(id)
  if (!editor) return
  engineService.evaluate(prepareEvaluationInput(editor.view.state.doc.toString()), id)
}

function renderInlineResults(tabId: string, lineResults: LineResult[]): void {
  const editor = tabEditorsSingleton.get(tabId)
  if (!editor) return
  const view = editor.view
  // Guard against destroyed editor (HMR unmount / tab close leaves stale reference)
  if (!view.dom || !view.dom.parentNode) return
  const effects: { from: number; to: number; deco: Decoration }[] = []
  for (const lr of lineResults) {
    if (lr.error) continue
    const isPending = lr.type === "Pending"
    // A Pending result formats to "" (see formatLineResultValue in
    // engineShared.ts — the queryKey must never be shown as if it were the
    // answer), so it needs its own branch instead of the `!lr.result` skip
    // other empty/non-evaluable lines take.
    if (!lr.result && !isPending) continue
    if ((lr.lineNumber ?? 1) > view.state.doc.lines) continue
    const line = view.state.doc.line(lr.lineNumber ?? 1)
    const text = isPending ? "…" : lr.result
    effects.push({ from: line.to, to: line.to, deco: Decoration.widget({ widget: new ResultWidget(text, lr.type, isPending), side: 1 }) })
  }
  // Always dispatch, even with an empty effects array: resultField's update()
  // rebuilds the ENTIRE decoration set from this list every time, so skipping
  // the dispatch when every line errored left whatever was previously
  // rendered stuck on screen after the line was edited into something that
  // no longer parses.
  view.dispatch({ effects: resultEffect.of(effects) })
}

function insertExample(expression: string): void {
  const editor = tabEditorsSingleton.get(useTabsStore.getState().activeTabId)
  if (!editor) return
  editor.view.dispatch({ changes: { from: 0, to: editor.view.state.doc.length, insert: expression } })
}

// Module-level map — CodeMirror EditorViews are imperative, DOM-attached
// objects that outlive React's render cycle; they're keyed by tabId and
// managed via effects below, not React state. Mirrors the Vue version's
// plain (non-reactive) `tabEditors`/`containerEls` maps.
const tabEditorsSingleton = new Map<string, TabEditor>()

export function EditorPane() {
  const tabs = useTabsStore((s) => s.tabs)
  const activeTabId = useTabsStore((s) => s.activeTabId)
  const editorCollapsed = useUiStore((s) => s.editorCollapsed)
  const result = useDiagnosticReportStore((s) => s.result)
  const cursorLine = useEditorStore((s) => s.cursorLine)
  const selectLine = usePipelineStore((s) => s.selectLine)

  // Self-healing attach: React (esp. StrictMode's dev-only double-invoke of
  // effects/refs) can call this ref callback more than once for the same
  // tab without a matching null-detach in between. Keying re-creation on
  // whether the tracked editor's DOM is STILL the one actually attached to
  // `el` (rather than just "does a map entry exist") means a repeat call
  // is a no-op, and a genuinely stale/orphaned entry gets torn down before
  // a fresh one is built — so exactly one live editor per tab survives
  // regardless of how many times this fires.
  const containerRefsCallback = (tabId: string) => (el: HTMLDivElement | null) => {
    if (!el) return
    const existing = tabEditorsSingleton.get(tabId)
    if (existing && existing.view.dom.parentElement === el) return
    if (existing) existing.view.destroy()
    el.replaceChildren()
    const tab = useTabsStore.getState().tabs.find((t) => t.id === tabId)
    const editor = createTabEditor(tabId, el, tab?.text ?? "")
    tabEditorsSingleton.set(tabId, editor)
    engineService.evaluate(tab?.text ?? "", tabId)
  }

  // Register this pane's imperative API for other components (ExamplesMenu) to call.
  useEffect(() => {
    useEditorStore.getState().setEditorRef({ insertExample })
    return () => useEditorStore.getState().setEditorRef(null)
  }, [])

  // Tear down editors for tabs that no longer exist (closed tabs).
  useEffect(() => {
    const currentIds = new Set(tabs.map((t) => t.id))
    for (const [tabId, editor] of tabEditorsSingleton) {
      if (!currentIds.has(tabId)) {
        editor.view.destroy()
        tabEditorsSingleton.delete(tabId)
      }
    }
  }, [tabs])

  useEffect(() => {
    return () => {
      for (const editor of tabEditorsSingleton.values()) editor.view.destroy()
      tabEditorsSingleton.clear()
    }
  }, [])

  // Update cursor line in pipeline when store changes.
  useEffect(() => {
    selectLine(cursorLine, false)
  }, [cursorLine, selectLine])

  // Render inline result decorators — `result` only ever reflects the
  // ACTIVE tab, so render into that tab's editor specifically.
  useEffect(() => {
    if (result) {
      const tabId = useTabsStore.getState().activeTabId
      requestAnimationFrame(() => renderInlineResults(tabId, result.lineResults))
    }
  }, [result])

  return (
    <main className={cn("flex min-h-0 flex-1 flex-col", editorCollapsed && "w-0 min-w-0 overflow-hidden")}>
      <div className="bg-card/40 flex h-9 shrink-0 items-center justify-between border-b px-3">
        <span className="text-muted-foreground flex items-center gap-1.5 text-xs font-semibold tracking-wide uppercase">
          <Code2 className="size-3.5" /> Editor
        </span>
        <ExamplesMenu />
      </div>
      <TabBar />
      <div className="relative min-h-0 flex-1">
        {tabs.map((tab) => (
          <div
            key={tab.id}
            ref={containerRefsCallback(tab.id)}
            className={cn("absolute inset-0", tab.id !== activeTabId && "hidden")}
          />
        ))}
      </div>
    </main>
  )
}
