// playground/src/components/DagTab.vue
<!--#region Component: DagTab — Dependency Graph Visualization -->
/**
 * DagTab.vue — Dependency graph visualization for variable tracking.
 *
 * Displays the DAG (Directed Acyclic Graph) of variable dependencies:
 * - Which variables each line reads and writes
 * - Which lines depend on (consume) each variable
 * - Data source dependencies for async resolution
 *
 * Uses a simple tree/list layout rather than a full SVG graph,
 * keeping the implementation lightweight while still conveying
 * the dependency topology.
 *
 * @component DagTab
 */
<!--#endregion -->

<template>
  <div class="tab-panel active" id="panel-dag">
    <div class="panel-toolbar">
      <span class="dag-count">
        {{ nodeCount }} variable{{ nodeCount !== 1 ? 's' : '' }} ·
        {{ edgeCount }} read{{ edgeCount !== 1 ? 's' : '' }} ·
        {{ sourceCount }} data source{{ sourceCount !== 1 ? 's' : '' }}
      </span>
      <span class="toggle-label" style="font-size:10px;color:var(--text-muted)">Dependency Graph</span>
    </div>
    <div class="panel-scroll">
      <span v-if="!hasData" class="empty">No DAG data available</span>

      <template v-else>
        <!-- Variable dependency list -->
        <div
          v-for="entry in varEntries"
          :key="entry.variable"
          class="dag-var-group"
          :class="{ expanded: expandedVars.has(entry.variable) }"
        >
          <div class="dag-var-header" @click="toggleVar(entry.variable)">
            <span class="msi msi-dense dag-var-toggle">{{ expandedVars.has(entry.variable) ? 'expand_more' : 'chevron_right' }}</span>
            <span
              class="dag-var-line"
              :class="{ 'dag-var-line-ext': !entry.producerLine }"
              :title="entry.producerLine ? 'Go to line ' + entry.producerLine : 'External variable (no producer)'"
              @click.stop="entry.producerLine ? selectLine(entry.producerLine) : undefined"
            >
              {{ entry.producerLine ? 'L' + entry.producerLine : 'ext' }}
            </span>
            <span class="dag-var-name">{{ entry.variable }}</span>
            <span class="dag-var-counts">
              <span v-if="entry.producerLine && entry.consumers.length === 0" class="dag-badge dag-badge-write" title="Defined but never read anywhere in this document">
                unused
              </span>
              <span v-else class="dag-badge dag-badge-read" :title="'Read by ' + entry.consumers.length + ' lines'">
                {{ entry.consumers.length }} read{{ entry.consumers.length !== 1 ? 's' : '' }}
              </span>
            </span>
          </div>
          <div v-if="expandedVars.has(entry.variable)" class="dag-var-body">
            <div class="dag-section-label">Consumers (lines that read this variable):</div>
            <div v-if="entry.consumers.length === 0" class="dag-empty-msg">No consumers</div>
            <div v-else class="dag-consumer-chips">
              <span v-for="ln in entry.consumers" :key="ln" class="dag-consumer-chip" @click="selectLine(ln)">
                L{{ ln }}
              </span>
            </div>

            <div v-if="entry.producerLine" class="dag-section-label" style="margin-top:8px">
              Producer (line that writes this variable):
            </div>
            <div v-if="entry.producerLine" class="dag-producer-chip" @click="selectLine(entry.producerLine)">
              L{{ entry.producerLine }}
            </div>
          </div>
        </div>

        <!-- Per-line data source dependencies: "what does THIS line depend
             on", complementing the section below ("what depends on THIS
             source") — uses dataSourceDeps, populated by the engine but
             previously never read anywhere in the playground. -->
        <div v-if="perLineDeps.length > 0" class="dag-section-header">
          Per-Line Dependencies
        </div>
        <div v-for="entry in perLineDeps" :key="entry.lineNumber" class="dag-var-group">
          <div class="dag-var-header" style="cursor: default;" @click.stop>
            <span
              class="dag-var-line"
              title="Go to this line"
              style="cursor: pointer;"
              @click="selectLine(entry.lineNumber)"
            >L{{ entry.lineNumber }}</span>
            <span class="dag-var-name">depends on</span>
            <span class="dag-consumer-chips">
              <span v-for="src in entry.sources" :key="src" class="dag-consumer-chip" style="cursor: default; color: var(--stage-async);"><span class="msi">sensors</span> {{ src }}</span>
            </span>
          </div>
        </div>

        <!-- Data source dependencies -->
        <div v-if="dataSourceEntries.length > 0" class="dag-section-header">
          Data Source Dependencies
        </div>
        <div
          v-for="entry in dataSourceEntries"
          :key="entry.key"
          class="dag-var-group"
          :class="{ expanded: expandedSources.has(entry.key) }"
        >
          <div class="dag-var-header" @click="toggleSource(entry.key)">
            <span class="dag-var-toggle">{{ expandedSources.has(entry.key) ? '▼' : '▶' }}</span>
            <span class="dag-var-name" style="color:var(--stage-async); display:inline-flex; align-items:center; gap:4px;"><span class="msi msi-dense">sensors</span> {{ entry.key }}</span>
            <span class="dag-var-counts">
              <span class="dag-badge dag-badge-async">{{ entry.consumers.length }} line{{ entry.consumers.length !== 1 ? 's' : '' }}</span>
            </span>
          </div>
          <div v-if="expandedSources.has(entry.key)" class="dag-var-body">
            <div class="dag-consumer-chips">
              <span v-for="ln in entry.consumers" :key="ln" class="dag-consumer-chip" @click="selectLine(ln)">
                L{{ ln }}
              </span>
            </div>
          </div>
        </div>
      </template>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, ref } from 'vue';
import { useDiagnosticReportStore } from '../stores/diagnosticReport.js';
import { usePipelineStore } from '../stores/pipeline.js';

const dr = useDiagnosticReportStore();
const pipeline = usePipelineStore();

const expandedVars = ref(new Set<string>());
const expandedSources = ref(new Set<string>());

function toggleVar(name: string): void {
  if (expandedVars.value.has(name)) expandedVars.value.delete(name);
  else expandedVars.value.add(name);
}

function toggleSource(key: string): void {
  if (expandedSources.value.has(key)) expandedSources.value.delete(key);
  else expandedSources.value.add(key);
}

function selectLine(ln: number): void {
  pipeline.selectLine(ln, true);
}

const hasData = computed(() => {
  const snap = dr.dagSnapshot;
  if (!snap) return false;
  return Object.keys(snap.consumers).length > 0 || Object.keys(snap.reads).length > 0 || Object.keys(snap.dataSourceConsumers).length > 0;
});

const nodeCount = computed(() => {
  const snap = dr.dagSnapshot;
  if (!snap) return 0;
  return Object.keys(snap.consumers).length;
});

const edgeCount = computed(() => {
  const snap = dr.dagSnapshot;
  if (!snap) return 0;
  let count = 0;
  for (const consumers of Object.values(snap.consumers)) count += consumers.length;
  return count;
});

const sourceCount = computed(() => {
  return Object.keys(dr.dagSnapshot?.dataSourceConsumers ?? {}).length;
});

interface VarEntry {
  variable: string;
  consumers: number[];
  producerLine: number | null;
}

const varEntries = computed<VarEntry[]>(() => {
  const snap = dr.dagSnapshot;
  if (!snap) return [];
  const allVars = new Set<string>();
  for (const v of Object.keys(snap.consumers)) allVars.add(v);
  for (const [, vars] of Object.entries(snap.writes)) vars.forEach(v => allVars.add(v));
  for (const [, vars] of Object.entries(snap.reads)) vars.forEach(v => allVars.add(v));

  // Build producer map: variable → line number that writes it
  const producers: Record<string, number> = {};
  for (const [lnStr, vars] of Object.entries(snap.writes)) {
    const ln = Number(lnStr);
    vars.forEach(v => { producers[v] = ln; });
  }

  return Array.from(allVars)
    .map(variable => ({
      variable,
      consumers: snap.consumers[variable] ?? [],
      producerLine: producers[variable] ?? null,
    }))
    .sort((a, b) => {
      // Sort by producer line number ascending; null producers last
      const la = a.producerLine ?? Infinity;
      const lb = b.producerLine ?? Infinity;
      if (la !== lb) return la - lb;
      // Tie-break by variable name
      return a.variable.localeCompare(b.variable);
    });
});

interface DataSourceEntry {
  key: string;
  consumers: number[];
}

interface PerLineDepsEntry {
  lineNumber: number;
  sources: string[];
}

/** Per-line "what data sources does this line depend on" — the inverse of dataSourceEntries below. */
const perLineDeps = computed<PerLineDepsEntry[]>(() => {
  const snap = dr.dagSnapshot;
  if (!snap?.dataSourceDeps) return [];
  return Object.entries(snap.dataSourceDeps)
    .map(([lnStr, sources]) => ({ lineNumber: Number(lnStr), sources }))
    .filter(e => e.sources.length > 0)
    .sort((a, b) => a.lineNumber - b.lineNumber);
});

const dataSourceEntries = computed<DataSourceEntry[]>(() => {
  const snap = dr.dagSnapshot;
  if (!snap) return [];
  return Object.entries(snap.dataSourceConsumers)
    .map(([key, consumers]) => ({
      key,
      consumers: [...consumers].sort((a, b) => a - b),
    }))
    .sort((a, b) => {
      // Sort by first consumer line number; no consumers last
      const fa = a.consumers[0] ?? Infinity;
      const fb = b.consumers[0] ?? Infinity;
      if (fa !== fb) return fa - fb;
      return a.key.localeCompare(b.key);
    });
});
</script>

<style scoped>
.dag-var-group {
  border-bottom: 1px solid rgba(255,255,255,0.06);
}
.dag-var-header {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 8px 12px;
  cursor: pointer;
  transition: background 0.15s;
  user-select: none;
}
.dag-var-header:hover {
  background: rgba(255,255,255,0.04);
}
.dag-var-toggle {
  color: var(--text-muted);
  width: 20px;
  flex-shrink: 0;
  justify-content: center;
}
.dag-var-line {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  min-width: 34px;
  font-size: 10px;
  font-weight: 600;
  font-family: 'SF Mono', 'Fira Code', 'Cascadia Code', monospace;
  padding: 1px 6px;
  border-radius: 4px;
  background: rgba(144, 224, 239, 0.12);
  color: #90e0ef;
  border: 1px solid rgba(144, 224, 239, 0.2);
  flex-shrink: 0;
  cursor: pointer;
  transition: background 0.15s;
}
.dag-var-line:hover {
  background: rgba(144, 224, 239, 0.2);
}
.dag-var-line-ext {
  background: rgba(107, 107, 117, 0.1);
  color: var(--text-muted);
  border-color: rgba(107, 107, 117, 0.15);
  font-weight: 400;
  font-size: 9px;
  text-transform: uppercase;
  letter-spacing: 0.3px;
}
.dag-var-line-ext:hover {
  background: rgba(107, 107, 117, 0.16);
}
.dag-var-name {
  font-family: 'SF Mono', 'Fira Code', 'Cascadia Code', monospace;
  font-size: 12px;
  color: var(--accent);
  flex: 1;
  min-width: 0;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.dag-var-counts {
  display: flex;
  gap: 6px;
  flex-shrink: 0;
}
.dag-badge {
  font-size: 9px;
  padding: 1px 6px;
  border-radius: 3px;
  font-weight: 500;
  letter-spacing: 0.3px;
}
.dag-badge-read {
  background: rgba(123, 223, 242, 0.15);
  color: #7bdff2;
}
.dag-badge-write {
  background: rgba(144, 224, 239, 0.15);
  color: #90e0ef;
}
.dag-badge-async {
  background: rgba(250, 255, 105, 0.15);
  color: #faff69;
}
.dag-var-body {
  padding: 0 12px 8px 28px;
}
.dag-section-label {
  font-size: 9px;
  color: var(--text-muted);
  text-transform: uppercase;
  letter-spacing: 0.5px;
  margin-bottom: 4px;
}
.dag-empty-msg {
  font-size: 10px;
  color: var(--text-muted);
  font-style: italic;
  padding: 4px 0;
}
.dag-consumer-chips {
  display: flex;
  flex-wrap: wrap;
  gap: 4px;
}
.dag-consumer-chip,
.dag-producer-chip {
  display: inline-flex;
  align-items: center;
  gap: 3px;
  padding: 2px 8px;
  font-size: 10px;
  font-family: 'SF Mono', 'Fira Code', 'Cascadia Code', monospace;
  border-radius: 3px;
  background: rgba(255,255,255,0.06);
  color: var(--text);
  cursor: pointer;
  transition: background 0.15s;
}
.dag-consumer-chip .msi { font-size: 13px; }
.dag-consumer-chip:hover,
.dag-producer-chip:hover {
  background: rgba(255,255,255,0.12);
}
.dag-section-header {
  padding: 10px 12px 6px;
  font-size: 10px;
  color: var(--text-muted);
  text-transform: uppercase;
  letter-spacing: 0.5px;
  font-weight: 600;
}
.dag-count {
  font-size: 10px;
  color: var(--text-muted);
}
</style>

// webapp/src/components/tabs/DagTab.tsx
import { useMemo, useState } from "react"
import { ChevronDown, ChevronRight, Radio } from "lucide-react"
import { useDiagnosticReportStore } from "@/stores/diagnosticReport"
import { usePipelineStore } from "@/stores/pipeline"
import { cn } from "@/lib/utils"

interface VarEntry {
  variable: string
  consumers: number[]
  producerLine: number | null
}

interface DataSourceEntry {
  key: string
  consumers: number[]
}

interface PerLineDepsEntry {
  lineNumber: number
  sources: string[]
}

/**
 * Dependency graph visualization for variable tracking — a simple tree/list
 * layout rather than a full SVG graph. Ported from playground's DagTab.vue.
 */
export function DagTab() {
  const snap = useDiagnosticReportStore((s) => s.dagSnapshot)
  const selectLineAction = usePipelineStore((s) => s.selectLine)
  const [expandedVars, setExpandedVars] = useState<Set<string>>(new Set())
  const [expandedSources, setExpandedSources] = useState<Set<string>>(new Set())

  function toggleVar(name: string) {
    setExpandedVars((prev) => {
      const next = new Set(prev)
      if (next.has(name)) next.delete(name)
      else next.add(name)
      return next
    })
  }

  function toggleSource(key: string) {
    setExpandedSources((prev) => {
      const next = new Set(prev)
      if (next.has(key)) next.delete(key)
      else next.add(key)
      return next
    })
  }

  function selectLine(ln: number) {
    selectLineAction(ln, true)
  }

  const hasData = !!snap && (Object.keys(snap.consumers).length > 0 || Object.keys(snap.reads).length > 0 || Object.keys(snap.dataSourceConsumers).length > 0)

  const nodeCount = snap ? Object.keys(snap.consumers).length : 0
  const edgeCount = snap ? Object.values(snap.consumers).reduce((sum, c) => sum + c.length, 0) : 0
  const sourceCount = Object.keys(snap?.dataSourceConsumers ?? {}).length

  const varEntries = useMemo<VarEntry[]>(() => {
    if (!snap) return []
    const allVars = new Set<string>()
    for (const v of Object.keys(snap.consumers)) allVars.add(v)
    for (const vars of Object.values(snap.writes)) vars.forEach((v) => allVars.add(v))
    for (const vars of Object.values(snap.reads)) vars.forEach((v) => allVars.add(v))

    const producers: Record<string, number> = {}
    for (const [lnStr, vars] of Object.entries(snap.writes)) {
      const ln = Number(lnStr)
      vars.forEach((v) => {
        producers[v] = ln
      })
    }

    return Array.from(allVars)
      .map((variable) => ({
        variable,
        consumers: snap.consumers[variable] ?? [],
        producerLine: producers[variable] ?? null,
      }))
      .sort((a, b) => {
        const la = a.producerLine ?? Infinity
        const lb = b.producerLine ?? Infinity
        if (la !== lb) return la - lb
        return a.variable.localeCompare(b.variable)
      })
  }, [snap])

  const perLineDeps = useMemo<PerLineDepsEntry[]>(() => {
    if (!snap?.dataSourceDeps) return []
    return Object.entries(snap.dataSourceDeps)
      .map(([lnStr, sources]) => ({ lineNumber: Number(lnStr), sources }))
      .filter((e) => e.sources.length > 0)
      .sort((a, b) => a.lineNumber - b.lineNumber)
  }, [snap])

  const dataSourceEntries = useMemo<DataSourceEntry[]>(() => {
    if (!snap) return []
    return Object.entries(snap.dataSourceConsumers)
      .map(([key, consumers]) => ({ key, consumers: [...consumers].sort((a, b) => a - b) }))
      .sort((a, b) => {
        const fa = a.consumers[0] ?? Infinity
        const fb = b.consumers[0] ?? Infinity
        if (fa !== fb) return fa - fb
        return a.key.localeCompare(b.key)
      })
  }, [snap])

  return (
    <div className="flex min-h-0 flex-1 flex-col">
      <div className="flex items-center gap-2 border-b px-4 py-1.5">
        <span className="text-muted-foreground text-xs">
          {nodeCount} variable{nodeCount !== 1 ? "s" : ""} · {edgeCount} read{edgeCount !== 1 ? "s" : ""} · {sourceCount} data source
          {sourceCount !== 1 ? "s" : ""}
        </span>
        <span className="text-muted-foreground/70 ml-auto text-[10px]">Dependency Graph</span>
      </div>

      <div className="flex-1 overflow-y-auto">
        {!hasData ? (
          <div className="text-muted-foreground p-3 text-sm">No DAG data available</div>
        ) : (
          <>
            {varEntries.map((entry) => {
              const isUnused = !!entry.producerLine && entry.consumers.length === 0
              return (
                <div key={entry.variable} className="border-b">
                  <div
                    onClick={() => toggleVar(entry.variable)}
                    className="hover:bg-muted/50 flex cursor-pointer items-center gap-2 px-3 py-2 select-none"
                  >
                    {expandedVars.has(entry.variable) ? <ChevronDown className="size-3.5" /> : <ChevronRight className="size-3.5" />}
                    <span
                      title={entry.producerLine ? `Go to line ${entry.producerLine}` : "External variable (no producer)"}
                      onClick={(e) => {
                        e.stopPropagation()
                        if (entry.producerLine) selectLine(entry.producerLine)
                      }}
                      className={cn(
                        "flex min-w-8.5 shrink-0 items-center justify-center rounded border px-1.5 py-0.5 font-mono text-[10px] font-semibold",
                        entry.producerLine
                          ? "cursor-pointer border-cyan-500/20 bg-cyan-500/10 text-cyan-600 dark:text-cyan-400"
                          : "text-muted-foreground border-muted-foreground/20 bg-muted text-[9px] font-normal tracking-wide uppercase",
                      )}
                    >
                      {entry.producerLine ? `L${entry.producerLine}` : "ext"}
                    </span>
                    <span className="text-primary min-w-0 flex-1 truncate font-mono text-sm">{entry.variable}</span>
                    <span className="flex shrink-0 gap-1.5">
                      {isUnused ? (
                        <span title="Defined but never read anywhere in this document" className="rounded bg-cyan-500/10 px-1.5 py-0.5 text-[9px] font-medium text-cyan-600 dark:text-cyan-400">
                          unused
                        </span>
                      ) : (
                        <span title={`Read by ${entry.consumers.length} lines`} className="rounded bg-sky-500/10 px-1.5 py-0.5 text-[9px] font-medium text-sky-600 dark:text-sky-400">
                          {entry.consumers.length} read{entry.consumers.length !== 1 ? "s" : ""}
                        </span>
                      )}
                    </span>
                  </div>
                  {expandedVars.has(entry.variable) && (
                    <div className="px-3 pb-2 pl-9">
                      <div className="text-muted-foreground mb-1 text-[9px] tracking-wide uppercase">Consumers (lines that read this variable):</div>
                      {entry.consumers.length === 0 ? (
                        <div className="text-muted-foreground py-1 text-[10px] italic">No consumers</div>
                      ) : (
                        <div className="flex flex-wrap gap-1">
                          {entry.consumers.map((ln) => (
                            <span
                              key={ln}
                              onClick={() => selectLine(ln)}
                              className="bg-muted hover:bg-accent cursor-pointer rounded px-2 py-0.5 font-mono text-[10px]"
                            >
                              L{ln}
                            </span>
                          ))}
                        </div>
                      )}
                      {entry.producerLine && (
                        <>
                          <div className="text-muted-foreground mt-2 mb-1 text-[9px] tracking-wide uppercase">Producer (line that writes this variable):</div>
                          <span
                            onClick={() => selectLine(entry.producerLine!)}
                            className="bg-muted hover:bg-accent inline-block cursor-pointer rounded px-2 py-0.5 font-mono text-[10px]"
                          >
                            L{entry.producerLine}
                          </span>
                        </>
                      )}
                    </div>
                  )}
                </div>
              )
            })}

            {perLineDeps.length > 0 && (
              <div className="text-muted-foreground px-3 py-2 text-[10px] font-semibold tracking-wide uppercase">Per-Line Dependencies</div>
            )}
            {perLineDeps.map((entry) => (
              <div key={entry.lineNumber} className="border-b">
                <div className="flex items-center gap-2 px-3 py-2">
                  <span
                    title="Go to this line"
                    onClick={() => selectLine(entry.lineNumber)}
                    className="flex min-w-8.5 cursor-pointer items-center justify-center rounded border border-cyan-500/20 bg-cyan-500/10 px-1.5 py-0.5 font-mono text-[10px] font-semibold text-cyan-600 dark:text-cyan-400"
                  >
                    L{entry.lineNumber}
                  </span>
                  <span className="text-primary font-mono text-sm">depends on</span>
                  <span className="flex flex-wrap gap-1">
                    {entry.sources.map((src) => (
                      <span key={src} className="flex items-center gap-1 rounded bg-amber-500/10 px-2 py-0.5 font-mono text-[10px] text-amber-600 dark:text-amber-400">
                        <Radio className="size-3" /> {src}
                      </span>
                    ))}
                  </span>
                </div>
              </div>
            ))}

            {dataSourceEntries.length > 0 && (
              <div className="text-muted-foreground px-3 py-2 text-[10px] font-semibold tracking-wide uppercase">Data Source Dependencies</div>
            )}
            {dataSourceEntries.map((entry) => (
              <div key={entry.key} className="border-b">
                <div onClick={() => toggleSource(entry.key)} className="hover:bg-muted/50 flex cursor-pointer items-center gap-2 px-3 py-2 select-none">
                  {expandedSources.has(entry.key) ? <ChevronDown className="size-3.5" /> : <ChevronRight className="size-3.5" />}
                  <span className="flex flex-1 items-center gap-1 font-mono text-sm text-amber-600 dark:text-amber-400">
                    <Radio className="size-3.5" /> {entry.key}
                  </span>
                  <span className="rounded bg-amber-500/10 px-1.5 py-0.5 text-[9px] font-medium text-amber-600 dark:text-amber-400">
                    {entry.consumers.length} line{entry.consumers.length !== 1 ? "s" : ""}
                  </span>
                </div>
                {expandedSources.has(entry.key) && (
                  <div className="px-3 pb-2 pl-9">
                    <div className="flex flex-wrap gap-1">
                      {entry.consumers.map((ln) => (
                        <span key={ln} onClick={() => selectLine(ln)} className="bg-muted hover:bg-accent cursor-pointer rounded px-2 py-0.5 font-mono text-[10px]">
                          L{ln}
                        </span>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            ))}
          </>
        )}
      </div>
    </div>
  )
}
